### ISSUE TITLE
flac-linux-x86 file not found

### ISSUE THREAD

**Issue by EssamTarik** [Uberi/speech_recognition#118]
i started a virtualenv with python3 on it
installed pocketsphinx,pyaudio and speech_recognition using pip
then ran `python -m speech_recognition`

and ran into this

`FileNotFoundError: [Errno 2] No such file or directory: '/home/scriptus/testmic/lib/python3.4/site-packages/speech_recognition/flac-linux-x86'`

please note that the file exists when i used `ls` command
```
VirtualBox:~/testmic$ ls '/home/scriptus/testmic/lib/python3.4/site-packages/speech_recognition/flac-linux-x86'
/home/scriptus/testmic/lib/python3.4/site-packages/speech_recognition/flac-linux-x86

```

this is the full output : 

```
A moment of silence, please...
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (MIXER,'IEC958 Playback Default',0,0,0): No such file or directory
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (MIXER,'IEC958 Playback Default',0,0,0): No such file or directory
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (MIXER,'IEC958 Playback Default',0,0,0): No such file or directory
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
Set minimum energy threshold to 656.4502484086315
Say something!
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (MIXER,'IEC958 Playback Default',0,0,0): No such file or directory
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (MIXER,'IEC958 Playback Default',0,0,0): No such file or directory
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (MIXER,'IEC958 Playback Default',0,0,0): No such file or directory
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
Got it! Now to recognize it...
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/scriptus/testmic/lib/python3.4/site-packages/speech_recognition/__main__.py", line 16, in <module>
    value = r.recognize_google(audio)
  File "/home/scriptus/testmic/lib/python3.4/site-packages/speech_recognition/__init__.py", line 642, in recognize_google
    convert_width = 2 # audio samples must be 16-bit
  File "/home/scriptus/testmic/lib/python3.4/site-packages/speech_recognition/__init__.py", line 385, in get_flac_data
    ], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1459, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/home/scriptus/testmic/lib/python3.4/site-packages/speech_recognition/flac-linux-x86'

```

**Comment by Uberi** [comment]
That's weird, can you try out the following to narrow down the issue?

* Try running the example code outside of a virtualenv.
* Try one of the other example scripts, such as [this one](https://github.com/Uberi/speech_recognition/blob/master/examples/audio_transcribe.py)
* Are you sure you checked that it exists inside your VM? I noticed you're running this in VirtualBox.
* Check if it works when run as superuser. When it's allowed to, the library will do a more thorough search for the binaries.
* How did you install the library, exactly? Inside the VM, right?

As a temporary workaround, simply do `sudo apt-get install flac`, `yum install flac`, or your OS's equivalent of this.

**Comment by EssamTarik** [comment]
note : installing flac solved the problem inside and outside virtualenv

1- i got the same result outside virtualenv

2- this is weird , but the example resulted into this: 
`FileNotFoundError: [Errno 2] No such file or directory: '/home/scriptus/testmic/english.wav'
`

3- all the output i sent was actually from the virtual machine , i sent the issue from it

4- superuser gives the same error

5 - 

i installed lubuntu 15.10 on a virtualbox VM , then
im gonna rebuild the virtualenv and share it with u , step by step

```
sudo apt-get install python3-pip
virtualenv --no-site-packages --python=python3 testmic
cd testmic
source bin/activate
pip3 install pocketsphinx
pip3 install pyaudio
pip3 install speechrecognition
python3 -m speech_recognition
```
with flac installed it works , without it doesnt

**Comment by Uberi** [comment]
Running the same commands on Ubuntu 16.04 did not manifest the issue. In fact, the example works quite fine out of the box.

Perhaps the output of `ls -l /home/scriptus/testmic/lib/python3.4/site-packages/speech_recognition` would be useful?

**Comment by EssamTarik** [comment]
well , i got rid of that VM and decided to start from scratch
you were right , it worked just fine this time , i have no idea what was wrong with the previous installation

as for the example , i just forgot to include an "english.wav" file in the directory , so all is fine now :smiley:

**Comment by Uberi** [comment]
Huh, well glad it works now, please do re-open if it happens again!
