### ISSUE TITLE
microphone_recognition.py hangs on "Say something!"

### ISSUE THREAD

**Issue by xMTinkerer** [Uberi/speech_recognition#124]
Steps to reproduce
------------------

I updated `microphone_recognition.py` to reflect the output of `PyAudio.get_device_info_by_index` to use `device_index = 2` and `sample_rate - 48000` when instantiating the `Microphone` like so:
```
# obtain audio from the microphone
r = sr.Recognizer()
with sr.Microphone( device_index = 2, sample_rate = 48000 ) as source:
    print("Say something!")
    audio = r.listen( source )
```

1. `python3 microphone_recognition.py`
2. Output:
```
pi@raspberrypi:~/Tinkering/python $ python3 microphone_recognition.py 
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.front.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
Say something!
```

Expected behaviour
------------------
I was thinking this would spit out text of the words I spoke. 

Actual behaviour
----------------
Indefinitely hangs with no further output.

System information
------------------
```
pi@raspberrypi:~/Tinkering $ python3 -V
Python 3.4.2
pi@raspberrypi:~/Tinkering $ 
pi@raspberrypi:~/Tinkering $ python3 -c "import speech_recognition as sr;print(sr.__version__)"
3.4.6
pi@raspberrypi:~/Tinkering $ 
pi@raspberrypi:~/Tinkering $ python3 -c "import pyaudio as p;print(p.__version__)"
0.2.9
pi@raspberrypi:~/Tinkering $ 
```

I compiled pocketsphinx from source.

I can successfully use `arecord` and `aplay`:
```
arecord -vvv -d 10 --device hw:1,0 --format s16_le --channels 2 --rate 48000 arecord_test.wav
```
```
aplay arecord_test.wav
```
And pyaudio can record (although very hard to hear due to garbled speech and audio/static interference)
Code:
```
import pyaudio
import wave
 
FORMAT = pyaudio.paInt16
CHANNELS = 1
RATE = 48000 #44100
CHUNK = 1024
RECORD_SECONDS = 5
WAVE_OUTPUT_FILENAME = "pyaudio_test.wav"
 
audio = pyaudio.PyAudio()
 
# start Recording
stream = audio.open(format=FORMAT, channels=CHANNELS,
                rate=RATE, input=True,
                frames_per_buffer=CHUNK)
print "recording..."
frames = []
 
for i in range(0, int( RATE / CHUNK * RECORD_SECONDS ) ):
    data = stream.read( CHUNK, exception_on_overflow = False )
    frames.append(data)
print "finished recording"
 
 
# stop Recording
stream.stop_stream()
stream.close()
audio.terminate()
 
waveFile = wave.open(WAVE_OUTPUT_FILENAME, 'wb')
waveFile.setnchannels(CHANNELS)
waveFile.setsampwidth(audio.get_sample_size(FORMAT))
waveFile.setframerate(RATE)
waveFile.writeframes(b''.join(frames))
waveFile.close()
```

**Comment by xMTinkerer** [comment]
Hey, no problem. That template is nice. 

Nice, that `r.energy_threshold = 4000` at least got it to do something. pocketsphinx gives me something really off and every time I run that `microphone_recognition.py` google throws the unknown value error. 

Yea, I'm really thinking it is a problem with pyaudio generally. Running this code produces some serious artifacts. 
```python
import pyaudio
import wave
 
FORMAT = pyaudio.paInt16
CHANNELS = 2
RATE = 44100
CHUNK = 1024
RECORD_SECONDS = 5
WAVE_OUTPUT_FILENAME = "pyaudio_test.wav"
 
audio = pyaudio.PyAudio()
 
# start Recording
stream = audio.open(format=FORMAT, channels=CHANNELS,
                rate=RATE, input=True,
                frames_per_buffer=CHUNK)
print( "recording..." )
frames = []
 
for i in range(0, int( RATE / CHUNK * RECORD_SECONDS ) ):
    data = stream.read( CHUNK, exception_on_overflow = False )
    frames.append(data)
print( "finished recording" )
 
 
# stop Recording
stream.stop_stream()
stream.close()
audio.terminate()
 
waveFile = wave.open(WAVE_OUTPUT_FILENAME, 'wb')
waveFile.setnchannels(CHANNELS)
waveFile.setsampwidth(audio.get_sample_size(FORMAT))
waveFile.setframerate(RATE)
waveFile.writeframes(b''.join(frames))
waveFile.close()
```

I've attached the [pyaudio_test.wav.zip](https://github.com/Uberi/speech_recognition/files/301543/pyaudio_test.wav.zip) and the artifacts in there sound very similar to the `microphone-results.wav` I recorded using your snippet above. Again, pointing to pyaudio. 

Just for kicks, when I run your Recognizer code on `x.wav`, I get:
```
Traceback (most recent call last):
  File "deleteme.py", line 7, in <module>
    print( r.recognize_google( audio ) )
  File "/usr/local/lib/python3.4/dist-packages/speech_recognition/__init__.py", line 672, in recognize_google
    if "alternative" not in actual_result: raise UnknownValueError()
speech_recognition.UnknownValueError
```

I'm wondering if this is a raspberry pi issue. [This stackexchange post](http://dsp.stackexchange.com/a/13732) talks about possible issues with the hardware. 

So, any ideas would be helpful, but I think I'll post this over on stackoverflow as my issue is not with this library. 

I must say though I do like how you've abstracted the hard bits out. So if I ever get this working, I'll look to using your library. Looks great!

**Comment by Uberi** [comment]
I have to admit, I've never seen this happen before.

A few things worth trying, maybe:

* Recording with a larger `CHUNK` value, like 4096 or even 8192 (it's possible that the script can't keep up with the audio as it's coming in, and it's skipping frames as a result - you can check if this is the case by removing the `exception_on_overflow` parameter).
* Using `CHANNELS = 2` instead of `CHANNELS = 1` - you seem to have a stereo mic, so maybe it's a bit fickle about being read as stereo?

Presumably, since `arecord` and `aplay` don't have these artifacts, it's something to do with these settings.

**Comment by xMTinkerer** [comment]
Ok, i'm pretty sure it is an issue with pyaudio. I'll dig there.

**Comment by krishnakanthpps** [comment]
@xMTinkerer  have you been able to solve this. I am pretty this is my issue as well.

**Comment by xMTinkerer** [comment]
Hey @krishnakanthpps, sorry for the delay in getting back to you. I can't seem to find anything really helpful in my notes and I abandoned this project after moving house and getting deep into other things. I managed to dig up this obscurity, not sure if it will help or not:

----

pyaudio in apt-get is not 2.0.9 needed. Also, according to [this post](https://groups.google.com/forum/#!topic/pyo-discuss/ptp_m39ACpI), the libportaudio might be too new. This worked

```
sudo apt-get install portaudio19-dev

sudo pip3 install pyaudio
```

Doh... pip was using python 2. So, need to get python3-pip:

```
sudo apt-get install python3-pip

sudo pip3 install SpeechRecognition
```

**Comment by Satyanshu1995** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/50285111/59707721-d3b56500-9220-11e9-873b-2d4f04bc6fb6.png)

    with sr.Microphone() as source():
        ^
SyntaxError: can't assign to function call
please someone help me.. i Already install pyaudio later version but still it is showing error.

**Comment by Mahershi** [comment]
Setting/Increasing chunk_size to 8192 worked for me.

**Comment by DhimanGhosh** [comment]
source should be a variable but not a function call
