### ISSUE TITLE
Error in converting a speech to text file to an exe

### ISSUE THREAD

**Issue by Dhrumogha** [Uberi/speech_recognition#146]
## Steps to reproduce

I tried converting a speech_recognition file to an exe using cx_Freeze (as part of a larger project). I created the setup.py file (attached) and the exe file using `python setup.py build`. When I run the exe file, this is the error I get

```
D:\PythonLocal\SIHI>build\exe.win32-3.3\voiceToText
A moment of silence, please...
Set minimum energy threshold to 253.35098498366372
Say something!
Got it! Now to recognize it...
Traceback (most recent call last):
  File "C:\Python33\Lib\subprocess.py", line 1105, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
    exec(code, m.**dict**)
  File "voiceToText.py", line 16, in <module>
    value = r.recognize_google(audio)
  File "C:\Python33\lib\site-packages\speech_recognition__init__.py", line 642, in recognize_google
    convert_width = 2 # audio samples must be 16-bit
  File "C:\Python33\lib\site-packages\speech_recognition__init__.py", line 385, in get_flac_data
    ], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "C:\Python33\Lib\subprocess.py", line 817, in **init**
    restore_signals, start_new_session)
  File "C:\Python33\Lib\subprocess.py", line 1111, in _execute_child
    raise WindowsError(*e.args)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

## Expected behaviour

Expected the exe file to execute normally, translaating my voice to text.
## Actual behaviour

An exception is thrown at the line 
value = r.recognize_google(audio)

[setup.zip](https://github.com/Uberi/speech_recognition/files/383695/setup.zip)
## System information

My **Python version** is 3.3.4.

My **SpeechRecognition library version** is 3.4.6

My **PyAudio library version** is 0.2.9

**Comment by Uberi** [comment]
This is caused by cx_freeze being unable to find a FLAC executable. You can use the following setup script to make things work:

```python
import cx_Freeze

executables = [cx_Freeze.Executable("voiceToText.py")]

import speech_recognition as sr
from os import path
base_path = path.dirname(path.abspath(sr.__file__))

cx_Freeze.setup(
    name="Sing it-Hear it",
    options={
        "build_exe": {
            "packages":["speech_recognition", "pyaudio"],
            "include_files": [path.join(base_path, "flac-win32.exe"), path.join(base_path, "flac-mac"), path.join(base_path, "flac-linux-x86"), path.join(base_path, "flac-linux-x86_64")],
        }
    },
    executables = executables
)
```
