### ISSUE TITLE
Python3 PocketSphinx Setup

### ISSUE THREAD

**Issue by fbacker** [Uberi/speech_recognition#153]
Steps to reproduce
------------------

Run background example
https://github.com/Uberi/speech_recognition/blob/master/examples/background_listening.py

Expected behaviour
------------------

Listen to på voice and print it

Actual behaviour
----------------

Getting error
Sphinx error; missing PocketSphinx module: ensure that PocketSphinx is set up correctly.

System information
------------------

My **Operating System** is Mac OS X 10.11.6

My **Python version** is Python 3.5.1

My **SpeechRecognition library version** is 3.4.6

My **PyAudio library version** is 0.2.9

My **PocketSphinx version** is 0.1.1

I **installed from** pip3 install pocketsphinx

**Comment by Uberi** [comment]
What does the following code produce?

```python3
from pocketsphinx import pocketsphinx
from sphinxbase import sphinxbase
```

Does that give an error? If so, what is the error?

**Comment by fbacker** [comment]
Kidkic:Speech kidkic$ python3 Test.py 
	Traceback (most recent call last):
	  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinxbase/sphinxbase.py", line 32, in swig_import_helper
	    return importlib.import_module(mname)
	  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py", line 126, in import_module
	    return _bootstrap._gcd_import(name[level:], package, level)
	  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
	  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
	  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
	  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
	  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
	  File "<frozen importlib._bootstrap_external>", line 903, in create_module
	  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
	ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinxbase/_sphinxbase.cpython-35m-darwin.so, 2): Symbol not found: _ad_close
	  Referenced from: /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinxbase/_sphinxbase.cpython-35m-darwin.so
	  Expected in: flat namespace
	 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinxbase/_sphinxbase.cpython-35m-darwin.so
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "Test.py", line 1, in <module>
	    from pocketsphinx import pocketsphinx
	  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pocketsphinx/__init__.py", line 32, in <module>
	    from .pocketsphinx import *
	  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pocketsphinx/pocketsphinx.py", line 116, in <module>
	    import sphinxbase
	  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinxbase/__init__.py", line 32, in <module>
	    from .sphinxbase import *
	  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinxbase/sphinxbase.py", line 35, in <module>
	    _sphinxbase = swig_import_helper()
	  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinxbase/sphinxbase.py", line 34, in swig_import_helper
	    return importlib.import_module('_sphinxbase')
	  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py", line 126, in import_module
	    return _bootstrap._gcd_import(name[level:], package, level)
	ImportError: No module named '_sphinxbase'


Checking pip3

	Kidkic:Speech kidkic$ pip3 freeze
	pocketsphinx==0.1.1
	PyAudio==0.2.9
	SpeechRecognition==3.4.6

**Comment by Uberi** [comment]
Something seems to have gone wrong with your pocketsphinx install - I recommend building it from source, since the Python package doesn't work.

If the issue persists, I recommend opening an issue in the [pocketsphinx-python repo](https://github.com/cmusphinx/pocketsphinx-python).
