### ISSUE TITLE
cannot join current thread

### ISSUE THREAD

**Issue by m7mdcc** [Uberi/speech_recognition#194]
Hello @Uberi , Thanks for your work .. as i mentioned on #78 . i need to achieve to make bot say & stop listen to its self , here is my code  
```python
import speech_recognition as sr
from SpeechToText import SpeechToText


class Recognizer:
    def __init__(self, lang='en-US', ttslang='en', provider='bing'):
        self.language = lang
        self.ttslanguage = ttslang
        self.provider = provider
        self.r = sr.Recognizer()
        self.txty = None
        self.starting()

    def listen(self):
        self.m = sr.Microphone()
        try:
            # received audio data, now we'll recognize it using Google Speech Recognition
            with self.m as self.source:
                self.r.adjust_for_ambient_noise(self.source)
                self.r.pause_threshold = 0.5
                self.r.non_speaking_duration = self.r.pause_threshold - 0.1
        except KeyboardInterrupt:
            pass

        def handler(recognizer, audio):
            print("Callback called")
            self.handletext(audio)

        self.stop_listen = self.r.listen_in_background(self.m, handler)

    def handletext(self, audio):
        print("Handletext called")
        try:
            if self.provider == "bing":
                self.txty = self.r.recognize_bing(audio, key="key",
                                                  language=self.language)
            elif self.provider == "google":
                self.txty = self.r.recognize_google(audio, key="key",
                                                    language=self.language)
            elif self.provider == "sphinx":
                self.txty = self.r.recognize_sphinx(audio)

        except sr.UnknownValueError:
            print("Bot could not understand audio")

        except sr.RequestError as e:
            print("Could not request results from Speech Recognition service Provider; {0}".format(e))

        txtyto = "Hello I'm Frank How I can help you ? "
        if self.txty is not None:
            if "hello" in self.txty.lower():
                self.stop_listen()
                print("OK SAY SAY OK SAY SAY OK SAY SAY ")
                self.speechtotxt = SpeechToText(language=self.ttslanguage)
                self.speechtotxt.say(txtyto)
                self.listen()
            else:
                print("NO  NO")

    def starting(self):

        if True:
            print("ECHO START LISTENING")
            self.listen()
        while True:
            pass


recognizer = Recognizer(provider="bing", ttslang="en", lang="en-US")
```

for text to speech class 

```python
import os
from gtts import gTTS
import tempfile
import pygame
import time

class SpeechToText:
    def __init__(self, language='en'):
        self.language = language

    def say(self, phrase):
        tts = gTTS(text=phrase, lang=self.language)
        with tempfile.NamedTemporaryFile(suffix='.mp3', delete=True) as f:
            tmpfile = f.name
            print(tmpfile)
        tts.save(tmpfile)
        self.play_mp3(tmpfile)
        os.remove(tmpfile)

    def play_mp3(self, filename):
        pygame.mixer.init()
        sleepy = pygame.mixer.Sound(filename).get_length()
        pygame.mixer.music.load(filename)
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
            print("Playing!!! ")
        pygame.mixer.quit()
        time.sleep(sleepy)
```

When condition triggered " if "hello" in self.txty.lower():" its show error 

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/speech_recognition/__init__.py", line 603, in threaded_listen
    if running[0]: callback(self, audio)
  File "/var/www/python/speech/Recognizer.py", line 27, in handler
    self.handletext(audio)
  File "/var/www/python/speech/Recognizer.py", line 52, in handletext
    self.stop_listen()
  File "/usr/local/lib/python3.5/dist-packages/speech_recognition/__init__.py", line 607, in stopper
    listener_thread.join()  # block until the background thread is done, which can be up to 1 second
  File "/usr/lib/python3.5/threading.py", line 1051, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```

How i can solve this ? 

Thanks

**Comment by m7mdcc** [comment]
this is another example like #78 one 

`#!/usr/bin/env python3
import speech_recognition as sr
from gtts import gTTS
import tempfile
import pygame
import os
import time


def say(phrase):
    tts = gTTS(text=phrase, lang="en")
    with tempfile.NamedTemporaryFile(suffix='.mp3', delete=True) as f:
        tmpfile = f.name
        print(tmpfile)
    tts.save(tmpfile)
    play_mp3(tmpfile)
    os.remove(tmpfile)


def play_mp3(filename):
    pygame.mixer.init()
    # sleepy = pygame.mixer.Sound(filename).get_length()
    pygame.mixer.music.load(filename)
    pygame.mixer.music.play()
    while pygame.mixer.music.get_busy():
        pygame.time.Clock().tick(10)
        print("Playing!!! ")
    pygame.mixer.quit()


r = sr.Recognizer()
m = sr.Microphone()

try:
    print("A moment of silence, please...")
    with m as source:
        r.adjust_for_ambient_noise(source)
    print("Set minimum energy threshold to {}".format(r.energy_threshold))
    while True:
        print("Say something!")
        with m as source:
            audio = r.listen(source)
        print("Got it! Now to recognize it...")
        try:
            # recognize speech using Google Speech Recognition
            value = r.recognize_google(audio)

            # we need some special handling here to correctly print unicode characters to standard output
            if str is bytes:  # this version of Python uses bytes for strings (Python 2)
                say(phrase=value)
            else:  # this version of Python uses unicode for strings (Python 3+)
                say(phrase=value)
        except sr.UnknownValueError:
            print("Oops! Didn't catch that")
        except sr.RequestError as e:
            print("Uh oh! Couldn't request results from Google Speech Recognition service; {0}".format(e))
        time.sleep(0.5)  # sleep for a little bit
except KeyboardInterrupt:
    pass

`


its continue listen to its self

**Comment by Uberi** [comment]
The stop function can only be used on the main thread. You'll need to make sure it's called from there.
