### ISSUE TITLE
python -m speech_recognition missing imports

### ISSUE THREAD

**Issue by BLCKPSTV** [Uberi/speech_recognition#197]
Installation worked, same steps as I did with my macbook pro. On my macbook pro I can run the test. On my Imac it doesn't work. Both OSX Sierra?

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/usr/local/lib/python2.7/site-packages/speech_recognition/__init__.py", line 5, in <module>
    import io
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
```

**Comment by Uberi** [comment]
It seems like your Python installation is broken; see https://stackoverflow.com/questions/34386527/symbol-not-found-pycodecinfo-getincrementaldecoder for details. In short, run `hash -r python`.
