### ISSUE TITLE
Not able to list microphones

### ISSUE THREAD

**Issue by harsh8398** [Uberi/speech_recognition#244]
I ran this code in Ubuntu lts 16.04 (I'm using a virtualenv for this)
```python
import speech_recognition as sr
mic_list = sr.Microphone.list_microphone_names()
```
and I got this output error
```
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
```

**Comment by Uberi** [comment]
Hi @harsh8398,

The output above doesn't seem to identify the underlying issue, unfortunately. Do you get a list back from that function? An empty one? A traceback? A segfault? Does `arecord` manage to record properly?

A hunch: does it work if you uninstall/reinstall PyAudio?

**Comment by harsh8398** [comment]
Reinstalling PyAudio did not work.
and also I tried `arecord` and it works perfectly.

**Comment by harsh8398** [comment]
Also when I try to run this program program gets stuck at say something
```python
import speech_recognition as sr
from time import ctime
import time
import os
from gtts import gTTS
 
def speak(audioString):
    print(audioString)
    tts = gTTS(text=audioString, lang='en')
    tts.save("audio.mp3")
    os.system("mpg321 audio.mp3")
 
def recordAudio():
    # Record Audio
    r = sr.Recognizer()
    with sr.Microphone() as source:
        print("Say something!")
        audio = r.listen(source)
 
    # Speech recognition using Google Speech Recognition
    data = ""
    try:
        # Uses the default API key
        # To use another API key: `r.recognize_google(audio, key="GOOGLE_SPEECH_RECOGNITION_API_KEY")`
        data = r.recognize_sphinx(audio)
        print("You said: " + data)
    except sr.UnknownValueError:
        print("Google Speech Recognition could not understand audio")
    except sr.RequestError as e:
        print("Could not request results from Google Speech Recognition service; {0}".format(e))
 
    return data
 
def jarvis(data):
    if "how are you" in data:
        speak("I am fine")
 
    if "what time is it" in data:
        speak(ctime())
 
    if "where is" in data:
        data = data.split(" ")
        location = data[2]
        speak("Hold on , I will show you where " + location + " is.")
        os.system("chromium-browser https://www.google.nl/maps/place/" + location + "/&amp;")
 
# initialization
time.sleep(2)
speak("Hi , what can I do for you?")
while 1:
    data = recordAudio()
    jarvis(data)
```
output:
```
Hi , what can I do for you?
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layer 1, 2, and 3.
Version 0.3.2-1 (2012/03/25). Written and copyrights by Joe Drew,
now maintained by Nanakos Chrysostomos and others.
Uses code from various people. See 'README' for more!
THIS SOFTWARE COMES WITH ABSOLUTELY NO WARRANTY! USE AT YOUR OWN RISK!

Playing MPEG stream from audio.mp3 ...
MPEG 2.0 layer III, 32 kbit/s, 24000 Hz mono
                                                                            
[0:02] Decoding of audio.mp3 finished.
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
Say something!

```
Interrupting gives this traceback:
```
Traceback (most recent call last):
  File "jarvis.py", line 54, in <module>
    data = recordAudio()
  File "jarvis.py", line 21, in recordAudio
    audio = r.listen(source)
  File "/home/harsh8398/.virtualenvs/jarvis/lib/python3.5/site-packages/speech_recognition/__init__.py", line 577, in listen
    buffer = source.stream.read(source.CHUNK)
  File "/home/harsh8398/.virtualenvs/jarvis/lib/python3.5/site-packages/speech_recognition/__init__.py", line 160, in read
    return self.pyaudio_stream.read(size, exception_on_overflow=False)
  File "/home/harsh8398/.virtualenvs/jarvis/lib/python3.5/site-packages/pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
KeyboardInterrupt
```
and with this program:
```python
import speech_recognition
import pyttsx

speech_engine = pyttsx.init('espeak') # see http://pyttsx.readthedocs.org/en/latest/engine.html#pyttsx.init
speech_engine.setProperty('rate', 150)

def speak(text):
	speech_engine.say(text)
	speech_engine.runAndWait()

recognizer = speech_recognition.Recognizer()

def listen():
	with speech_recognition.Microphone() as source:
		recognizer.adjust_for_ambient_noise(source)
		audio = recognizer.listen(source)

	try:
		return recognizer.recognize_sphinx(audio)
		# or: return recognizer.recognize_google(audio)
	except speech_recognition.UnknownValueError:
		print("Could not understand audio")
	except speech_recognition.RequestError as e:
		print("Recog Error; {0}".format(e))

	return ""

speak("Say something!")
speak("I heard you say " + listen())

```
It first says 'say something' and then after a sec or two ends at middle of saying 'I h..(ends)' without any traceback:
```
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
```

**Comment by Uberi** [comment]
Hi @harsh8398,

Can you post the output of the following?

```bash
python -c 'import speech_recognition as sr; print(sr.Microphone.list_microphone_names())'
```

Also, the microphone index may be incorrect - can you try the following? https://github.com/Uberi/speech_recognition/#the-recognizer-hangs-on-recognizer_instancelisten-specifically-when-its-calling-microphonemicrophonestreamread

**Comment by harsh8398** [comment]
Output for `python -c 'import speech_recognition as sr; print(sr.Microphone.list_microphone_names())'`:
```
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
['HDA Intel PCH: ALC3241 Analog (hw:0,0)', 'HDA Intel PCH: HDMI 0 (hw:0,3)', 'HDA Intel PCH: HDMI 1 (hw:0,7)', 'HDA Intel PCH: HDMI 2 (hw:0,8)', 'sysdefault', 'front', 'surround40', 'surround51', 'surround71', 'hdmi', 'pulse', 'dmix', 'default']
``
I tried all available indexes but it didn't work this is really confusing me in my sound setting it is showing inbuild microphone input pulses- [Screenshot](https://i.imgur.com/YldxsXE.png)

And here is `alsa config PCM list` [Screenshot](https://i.imgur.com/gff1Ayo.png). I also tried to comment it out as mentioned in troubleshooting but it just makes that particular line disappear from that error message.

**Comment by JoshKellyVFX** [comment]
Hi all,

I also ran python3 -c 'import speech_recognition as sr; print(sr.Microphone.list_microphone_names())'
and am getting a similar error to you. Any clue what could be causing it?
```
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
['HDA Intel PCH: ALC255 Analog (hw:0,0)', 'HDA Intel PCH: HDMI 0 (hw:0,3)', 'HDA Intel PCH: HDMI 1 (hw:0,7)', 'HDA Intel PCH: HDMI 2 (hw:0,8)', 'sysdefault', 'hdmi', 'pulse', 'default']

```

**Comment by harsh8398** [comment]
@JoshKellyVFX Sorry, I've been also waiting for a response for solving this problem. I've tried running this in windows and it works perfectly there. By the way @Uberi should I try changing `alsa` with other alternatives?

**Comment by JoshKellyVFX** [comment]
I'm running on Ubuntu myself and that's where I'm having the most of my issues.

**Comment by Uberi** [comment]
Hi @harsh8398,

Seems like it's an ALSA configuration issue - if `sr.Microphone(device_index=0)` doesn't work, you may want to try the suggestion [in this post](http://mailman.alsa-project.org/pipermail/alsa-devel/2016-January/103319.html). Does that change the result?

**Comment by harsh8398** [comment]
Ok, so I recently removed my 16.04 version (accidentally formatted my drive silly me!) and installed 17.10 and its working fine. I don't know what was the problem but it is working fine now on the new installation. Thanks for your support! So if you want to close this issue then you can or keep open if the problem is still there for others.

**Comment by Uberi** [comment]
Great to hear!

**Comment by lstuma** [comment]
When I try to list microphones I never get a response. Been waiting for over two hours now and nothing:

```
$ python -c 'import speech_recognition as sr; print(sr.Microphone.list_microphone_names())'
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
```
