### ISSUE TITLE
[Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by francescovallone** [Uberi/speech_recognition#264]
Steps to reproduce
------------------

```
import speech_recognition as sr
from os import path


AUDIO_FILE = path.join(path.dirname(path.realpath(__file__)), "audio.wav")

with sr.AudioFile(AUDIO_FILE) as source:
    audio = r.record(source)


print(r.recognize_google(audio, language="ja"))
```

Expected behaviour
------------------

It should print the text of the audio

Actual behaviour
----------------

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 936, in _send_output
    self.send(message_body)
  File "/usr/lib/python3.5/http/client.py", line 908, in send
    self.sock.sendall(data)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/francesco/.local/lib/python3.5/site-packages/speech_recognition/__init__.py", line 762, in recognize_google
    response = urlopen(request, timeout=self.operation_timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lyrics.py", line 20, in <module>
    print(r.recognize_google(audio, language="ja"))
  File "/home/francesco/.local/lib/python3.5/site-packages/speech_recognition/__init__.py", line 766, in recognize_google
    raise RequestError("recognition connection failed: {}".format(e.reason))
speech_recognition.RequestError: recognition connection failed: [Errno 104] Connection reset by peer
```

System information
------------------

My **system** is elementary OS 0.4.1 Loki.

My **Python version** is 3.5.2 . (You can check this by running `python -V`.)

My **Pip version** is 8.1.1 . (You can check this by running `pip -V`.)

My **SpeechRecognition library version** is 3.7.1 .

My **PyAudio library version** is 0.2.11 .

**Comment by Uberi** [comment]
Are you connected to the internet, and able to access Google?

**Comment by francescovallone** [comment]
Yes, I'm able to connect to internet and I can use Google

**Comment by Uberi** [comment]
It appears that your network is dropping the connection - do any of the other APIs work? For example, Wit.ai? Do the example/demo scripts work?

**Comment by RyanQuey** [comment]
@francescovallone I'm having this error as well actually, can you tell me why you closed this? Were you able to solve it?

**Comment by francescovallone** [comment]
I didn't solve it. Actually, I don't work on this project anymore so I closed it. Sorry
