### ISSUE TITLE
httplib.BadStatusLine error on Windows machine

### ISSUE THREAD

**Issue by chitralekha18** [Uberi/speech_recognition#273]
I am running a script to do recognition for 10 seconds files for my research. The google recognizer intermittently gives httplib.BadStatusLine error. I guess the problem is it loses connection intermittently - doesn't happen always. **So my question is can I catch this error, and retry sending the file after a second or so?**

**This is the error:**
Traceback (most recent call last):
  File "test.py", line 684, in <module>
    RecognitionAndMatching(initialsegmentfolder,file,finalsegmentfolder,songname,lyricsfolder,transcriptfile,fout1,fout2,fout3,fout4)
  File "test.py", line 515, in RecognitionAndMatching
    dict = r.recognize_google(audio, show_all=True)
  File "C:\Users\workshop\Anaconda2\lib\site-packages\speech_recognition\__init__.py", line 762, in recognize_google
    response = urlopen(request, timeout=self.operation_timeout)
  File "C:\Users\workshop\Anaconda2\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\workshop\Anaconda2\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Users\workshop\Anaconda2\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Users\workshop\Anaconda2\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Users\workshop\Anaconda2\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Users\workshop\Anaconda2\lib\urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "C:\Users\workshop\Anaconda2\lib\httplib.py", line 1121, in getresponse
    response.begin()
  File "C:\Users\workshop\Anaconda2\lib\httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "C:\Users\workshop\Anaconda2\lib\httplib.py", line 402, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''

**And here's my code-snippet**
r = sr.Recognizer()
                with sr.AudioFile(AUDIO_FILE) as source:
                    audio = r.record(source)  # read the entire audio file
try:
     dict = r.recognize_google(audio, show_all=True)
except sr.UnknownValueError:
        print("Google Speech Recognition could not understand audio")
except sr.RequestError as e:
        print("Could not request results from Google Speech Recognition service; {0}".format(e))

**Comment by chitralekha18** [comment]
Ok the way to catch this error is:

from httplib import BadStatusLine

try:
    ......

except BadStatusLine:
       print "could not fetch Google URL"

**Comment by Uberi** [comment]
Hope the connection issues are resolved for you! I will close this issue for now, but feel free to reopen if they persist.
