### ISSUE TITLE
Errors after Quickstart ?

### ISSUE THREAD

**Issue by jehoshua7** [Uberi/speech_recognition#291]
Steps to reproduce
------------------

1. (How do you make the issue happen? Does it happen every time you try it?)

I'm wanting to transcribe audio files and found the page at https://pypi.python.org/pypi/SpeechRecognition/ , and downloaded the file SpeechRecognition-3.7.1-py2.py3-none-any.whl
Then tried the command for the Quickstart - pip install SpeechRecognition ; got some error and had to run 'sudo apt install python-pip'
Tried the command again - pip install SpeechRecognition , it installed okay, so I issued the command 'python -m speech_recognition' and got the following errors:

-----------------
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/********/.local/lib/python2.7/site-packages/speech_recognition/__main__.py", line 4, in <module>
    m = sr.Microphone()
  File "/home/********/.local/lib/python2.7/site-packages/speech_recognition/__init__.py", line 79, in __init__
    self.pyaudio_module = self.get_pyaudio()
  File "/home/********/.local/lib/python2.7/site-packages/speech_recognition/__init__.py", line 110, in get_pyaudio
    raise AttributeError("Could not find PyAudio; check installation")
AttributeError: Could not find PyAudio; check installation
----------------------

System information
------------------

(Delete all the statements that don't apply.)

My **system** is Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
kernel version 4.4.0-101-generic

My **Python version** is Python 2.7.12

My **Pip version** is pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)

My **SpeechRecognition library version** is 3.7.1

I don't have PyAudio installed.

I don't have PocketSphinx installed. Have just checked in synaptic. Could that be the problem ? ?

**Comment by jehoshua7** [comment]
Used synaptic to install these packages ..

pocketsphinx
python-pyaudio
python-pyaudio3

Then tried this command again ..

$ 'python -m speech_recognition'

>Traceback (most recent call last):                                                                                                                                                              
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main                                                                                                                          
    "__main__", fname, loader, pkg_name)                                                                                                                                                        
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code                                                                                                                                     
    exec code in run_globals                                                                                                                                                                    
  File "/home/********/.local/lib/python2.7/site-packages/speech_recognition/__main__.py", line 4, in <module>                                                                                     
    m = sr.Microphone()                                                                                                                                                                         
  File "/home/********/.local/lib/python2.7/site-packages/speech_recognition/__init__.py", line 79, in __init__                                                                                    
    self.pyaudio_module = self.get_pyaudio()                                                                                                                                                    
  File "/home/********/.local/lib/python2.7/site-packages/speech_recognition/__init__.py", line 113, in get_pyaudio                                                                                
    raise AttributeError("PyAudio 0.2.11 or later is required (found version {})".format(pyaudio.__version__))                                                                                  
AttributeError: PyAudio 0.2.11 or later is required (found version 0.2.8)

Seems I need Python 2.8, but there is no 2.8 showing at https://www.python.org/downloads/ . Also, I have the latest PyAudio for Kubuntu.

Where to from here please ?

**Comment by jehoshua7** [comment]
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
Kernel release 4.4.0-101-generic
Python 2.7.12
pip 9.0.1 from /home/********/.local/lib/python2.7/site-packages (python 2.7)
Speech_Recognition version is 3.7.1
PYAudio version is 0.2.11

Have now been able to install/update a few packages to enable executing the test without errors. 

python -m speech_recognition

resulted in prompts for voice input from the microphone. I found the accuracy quite good, thanks to the develeopers.
