### ISSUE TITLE
ModuleNotFoundError: No module named 'speech_recognition' in Fedora 26

### ISSUE THREAD

**Issue by rajnishcoder** [Uberi/speech_recognition#294]
I already installed `speech_recognition` and trying to import `speech_recognition` it gave me `ModuleNotFoundError: No module named 'speech_recognition'`

**Hear is my python code**

```
import speech_recognition as sr

r = sr.Recognizer()

with sr.Microphone() as mp:
    print('say')
    audio = r.listen(mp)
    
try:
    print(r.recognize_google(audio))

except:
    pass

```
Here is console error

> Traceback (most recent call last):
> 
>   File "<ipython-input-7-9e3bdf5986c0>", line 1, in <module>
>     runfile('/home/coder/Documents/python/speechtotext.py', wdir='/home/coder/Documents/python')
> 
>   File "/usr/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 710, in runfile
>     execfile(filename, namespace)
> 
>   File "/usr/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 101, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "/home/coder/Documents/python/speechtotext.py", line 8, in <module>
>     import speech_recognition as sr
> 
> ModuleNotFoundError: No module named 'speech_recognition'

System information
------------------

My **system** is <Fedora 26>.

My **Python version** is <Python 2.7.14> in fedora 26 but I upgraded it to 3.6 

My **Pip version** is <pip 9.0.1>. 

My **SpeechRecognition library version** is <3.7.1>.

**Comment by Uberi** [comment]
Hi @rajnishcoder,

Can you post the following information?

1. The path that `speech_recognition` has been installed to.
2. The output of `python -c "import sys; print(sys.path)"`.
3. How you installed `speech_recognition` (e.g., using `pip` vs. using `pip3`).

I would also make sure first of all that it's installed with `pip3` rather than `pip`, since IIRC that would default to installing for Python 2.

**Comment by Mardii-D-King** [comment]
Try `sudo pip3 install --upgrade speechrecognition`

**Comment by esitharth** [comment]
facing the same problem

**Comment by iamakhilk** [comment]
try pip3 install --upgrade speechrecognition

**Comment by 25shady** [comment]
i-got-the-same-problem-as @rajnishcoder -and-i had-tried-to-resolve-it-by-using-pip3-then-also-i-am-getting-same-module-not-found-error

**Comment by 25shady** [comment]
facing-same-problem-even-after upgrading-speech-recognition-using-pip3

**Comment by gabbsoares** [comment]
![image](https://user-images.githubusercontent.com/42794581/45091392-ad3a9900-b0e8-11e8-8dd5-988e91552593.png)

cmd say this but i have the same error 

>     import speech_recognition as sr
> ModuleNotFoundError: No module named 'speech_recognition'

**Comment by 25shady** [comment]
first-check-the-speech-recognition(sr)-file-from-the-given-path-from-your-terminal-in-that-folder-two-file-of-sr-is-their
1-is-speech_recognition
2-is-SpeechRecognition-3.8.1.dist-info
copy-this-both-file-and-paste-it-into-anaconda's-SITE-PACKAGE-file
remember-where-your-anaconda's-file-is
example-D:\anaconda\Lib\site-packages
the-above-mention-directory-is-where-my-anaconda-file-is

**Comment by sugatoray** [comment]
## Solution
Note: I am using a PC.
Use **`pip3 install --upgrade speechrecognition`** as pointed out by Mardii-D-King.

## Observation
'pip install SpeechRecognition' installed the package and I could also import it from **cmd** followed by checking its version: 
```
import speech_recognition as sr
sr.__version__
```
## However
Running the same from Jupyter Notebook threw the same error as mentioned above. So, trying the following solved it. Run this from inside Jupyter Notebook:
```
!pip3 install --upgrade speechrecognition
import speech_recognition as sr
sr.__version__
```

**And it was working for me...**

**Comment by staRk22** [comment]
You must have installed SpeechRecognition from Terminal - cmd and you must be using anaconda or other package libraries like that.
What has happened here is that your speech SpeechRecognition has installed in your python local directory. you have to copy it from there and paste it in your anaconda library.

Follow the steps:
1) go to C:\Python\Lib\site-packages
2) Copy files :1: speech_recognition
                      2: SpeechRecognition-3.8.1.dist-info
3) Paste it in your C:\anaconda\Lib\site-packages

This will fix the problem.

**Comment by Nahidahmed** [comment]
> You must have installed SpeechRecognition from Terminal - cmd and you must be using anaconda or other package libraries like that.
> What has happened here is that your speech SpeechRecognition has installed in your python local directory. you have to copy it from there and paste it in your anaconda library.
> 
> Follow the steps:
> 
> 1. go to C:\Python\Lib\site-packages
> 2. Copy files :1: speech_recognition
>    2: SpeechRecognition-3.8.1.dist-info
> 3. Paste it in your C:\anaconda\Lib\site-packages
> 
> This will fix the problem.

Thanks @staRk22 ...your solution works!!

**Comment by bishesh23** [comment]
@staRk22 where is this anaconda folder... i dont have...

**Comment by ramiresnas** [comment]
> Try `sudo pip3 install --upgrade speechrecognition`
thanks, work for me.

**Comment by alexmursa2013** [comment]
verify if you don't have a two version python installed ex: 3.7.3 (x64) and 3.7.4 (x32)
delete 3.7.3 and it is worked ok next

**Comment by uzzalmondal131** [comment]
If you use the python version bellow 3.x.x then try
sudo pip3 install --upgrade speechrecognition
And If you use pycharm or ID then go to File > Settings > Project: XX  > Project Interpreter > 

![Screenshot from 2019-08-22 13-22-08](https://user-images.githubusercontent.com/54393348/63496721-09582200-c4e0-11e9-9de0-6516691ba446.png)
3-f3e2f800-c4df-11e9-993a-f84730e16d12.png)

 -> install

**Comment by rsmahajan** [comment]
> first-check-the-speech-recognition(sr)-file-from-the-given-path-from-your-terminal-in-that-folder-two-file-of-sr-is-their
> 1-is-speech_recognition
> 2-is-SpeechRecognition-3.8.1.dist-info
> copy-this-both-file-and-paste-it-into-anaconda's-SITE-PACKAGE-file
> remember-where-your-anaconda's-file-is
> example-D:\anaconda\Lib\site-packages
> the-above-mention-directory-is-where-my-anaconda-file-is

This worked for me. Thanks.

**Comment by LivechessYahoo** [comment]
I have the same problem, but nothing helped me. I tried to upgrade the speechrecognition and copy/paste the files to anaconda path - to no avail... I need your advice people, thank you in advance!

**Comment by ayushboss1** [comment]
I have the same problem
Here is my solution 
1) I downloaded the file into right directory of anaconda. but still, it was not working. (If you have wrong directory path set it up at anaconda/lib/site_packages)
2) I went into the folder then I found out it is not speechrecogniton instead it is speech_recogniton. so I changed the name and it worked for me

**Comment by pnmartinez** [comment]
> Hi @rajnishcoder,
> 
> Can you post the following information?
> 
>     1. The path that `speech_recognition` has been installed to.
> 
>     2. The output of `python -c "import sys; print(sys.path)"`.
> 
>     3. How you installed `speech_recognition` (e.g., using `pip` vs. using `pip3`).
> 
> 
> I would also make sure first of all that it's installed with `pip3` rather than `pip`, since IIRC that would default to installing for Python 2.

To add on this, a general solution in case various Python versions are installed:
- Calling `pip` is shortcut for the pip script through default python version: `python -m pip install [package_to_install].
- It can be tricky to not mess up pip when managing various Python versions, so then pip and even pip3 do not install where you'd like it to be.
- In case python version aliases are properly set up, you can install easily to the Python version just by calling the un-shortened command. Say we want to install packages to Python 3.7, despite `python` calling a 2.7 build and `python3` calling a 3.8 build. Instead of calling `pip` or `pip3` shortcuts, which most likely are associated to those last ones, use the whole:
```
python3.7 -m pip install --upgrade [package]
```
python3.7 -m pip

**Comment by sscswapnil** [comment]
`import speech_recognition as sr`

this resolve my problem when I look into python site packages I realise the name os the package is different  and I tried Above one and it worked

**Comment by ArcticLilacFox** [comment]
All of this did not work for me. I **cannot** find SpeechRecognition in the installable packages for pyCharm. I have installed SpeechRecognition everywhere. In my pytorch environment, conda, python 3.6 as well. Nothing helped.
Changing my code from ```import speech_recognition as sr``` to ```import speechrecognition as sr``` did not make a difference.

**Comment by shaliniverma132** [comment]
I'm keep getting these errors below😑
Please help to resolve my problem
C:\python programs\Jarvis>python -u "c:\python programs\Jarvis\jarvis.py"
Traceback (most recent call last):
  File "c:\python programs\Jarvis\jarvis.py", line 2, in <module>
    import SpeechRecognition
ModuleNotFoundError: No module named 'SpeechRecognition'

**Comment by Rushil-Sharma** [comment]
what i did is installed python again but if it still doesnt work then do not use it

**Comment by JaysreeeRoyal** [comment]
> > You must have installed SpeechRecognition from Terminal - cmd and you must be using anaconda or other package libraries like that.
> > What has happened here is that your speech SpeechRecognition has installed in your python local directory. you have to copy it from there and paste it in your anaconda library.
> > Follow the steps:
> > 
> > 1. go to C:\Python\Lib\site-packages
> > 2. Copy files :1: speech_recognition
> >    2: SpeechRecognition-3.8.1.dist-info
> > 3. Paste it in your C:\anaconda\Lib\site-packages
> > 
> > This will fix the problem.
> 
> Thanks @staRk22 ...your solution works!!

**Comment by JaysreeeRoyal** [comment]
> You must have installed SpeechRecognition from Terminal - cmd and you must be using anaconda or other package libraries like that.
> What has happened here is that your speech SpeechRecognition has installed in your python local directory. you have to copy it from there and paste it in your anaconda library.
> 
> Follow the steps:
> 
> 1. go to C:\Python\Lib\site-packages
> 2. Copy files :1: speech_recognition
>    2: SpeechRecognition-3.8.1.dist-info
> 3. Paste it in your C:\anaconda\Lib\site-packages
> 
> This will fix the problem.

**Comment by JaysreeeRoyal** [comment]
I'm getting ModuleNotFoundError: No module named 'speech_recognition'
![Screenshot (4)](https://user-images.githubusercontent.com/74035301/98360104-478f2200-204f-11eb-948b-574564682d55.png)
![Screenshot (5)](https://user-images.githubusercontent.com/74035301/98360132-51b12080-204f-11eb-9ced-7ba579888180.png)

SpeechRecognition is installed but I could'nt find speechrecognition file.
Pleassss help me

**Comment by Rushil-Sharma** [comment]
you have to go to where it is installed and check if it is running there without an error
or you must have changed the code

**Comment by qertyuiop12345678** [comment]
> try pip3 install --upgrade speechrecognition

I used repl.it and I have to manually install the package, and that made it work...

**Comment by sebastiankarame888** [comment]
I too, am facing the same problem. :(

**Comment by sebastiankarame888** [comment]
Speech recognition is already satisfied?

**Comment by Amira-Abidi** [comment]
> If you use the python version bellow 3.x.x then try
> sudo pip3 install --upgrade speechrecognition
> And If you use pycharm or ID then go to File > Settings > Project: XX > Project Interpreter >
> 
> ![Screenshot from 2019-08-22 13-22-08](https://user-images.githubusercontent.com/54393348/63496721-09582200-c4e0-11e9-9de0-6516691ba446.png)
> 3-f3e2f800-c4df-11e9-993a-f84730e16d12.png)
> 
> -> install Package

work for me , thanks

**Comment by GeorgiVL** [comment]
> > You must have installed SpeechRecognition from Terminal - cmd and you must be using anaconda or other package libraries like that.
> > What has happened here is that your speech SpeechRecognition has installed in your python local directory. you have to copy it from there and paste it in your anaconda library.
> > Follow the steps:
> > 
> > 1. go to C:\Python\Lib\site-packages
> > 2. Copy files :1: speech_recognition
> >    2: SpeechRecognition-3.8.1.dist-info
> > 3. Paste it in your C:\anaconda\Lib\site-packages
> > 
> > This will fix the problem.
> 
> Thanks @staRk22 ...your solution works!!

> Thanks @staRk22 that helped on me as well :)

**Comment by Project-fil** [comment]
You must have installed SpeechRecognition from Terminal - cmd and you must be using anaconda or other package libraries like that.
What has happened here is that your speech SpeechRecognition has installed in your python local directory. you have to copy it from there and paste it in your anaconda library.
Follow the steps:

go to C:\Python\Lib\site-packages
Copy files :1: speech_recognition
2: SpeechRecognition-3.8.1.dist-info
Paste it in your C:\anaconda\Lib\site-packages
This will fix the problem.

Thanks @staRk22 ...your solution works!!

Thanks @staRk22 that helped on me as well :)

Thanks a lot. it helped me a lot)))

**Comment by zahid60** [comment]
> If you use the python version bellow 3.x.x then try sudo pip3 install --upgrade speechrecognition And If you use pycharm or ID then go to File > Settings > Project: XX > Project Interpreter >
> 
> ![Screenshot from 2019-08-22 13-22-08](https://user-images.githubusercontent.com/54393348/63496721-09582200-c4e0-11e9-9de0-6516691ba446.png) 3-f3e2f800-c4df-11e9-993a-f84730e16d12.png)
> 
> -> install Package

Thank you ,its works

**Comment by miercolesalfonzo** [comment]
> pip3 install --upgrade speechrecognition

it happened to me too, i don't know what to do

**Comment by shreetheman2011** [comment]
> ## Solution
> Note: I am using a PC. Use **`pip3 install --upgrade speechrecognition`** as pointed out by Mardii-D-King.
> 
> ## Observation
> 'pip install SpeechRecognition' installed the package and I could also import it from **cmd** followed by checking its version:
> 
> ```
> import speech_recognition as sr
> sr.__version__
> ```
> 
> ## However
> Running the same from Jupyter Notebook threw the same error as mentioned above. So, trying the following solved it. Run this from inside Jupyter Notebook:
> 
> ```
> !pip3 install --upgrade speechrecognition
> import speech_recognition as sr
> sr.__version__
> ```
> 
> **And it was working for me...**

This is the answer, it worked very well in my case. And I was experiencing same problem. Thank you very much for that answer!
