### ISSUE TITLE
Stream closed

### ISSUE THREAD

**Issue by prasadnarasimhan74** [Uberi/speech_recognition#312]
D:\speech\speech_recognition\examples>py write_audio.py
Say something!
Traceback (most recent call last):
  File "write_audio.py", line 11, in <module>
    audio = r.listen(source)
  File "C:\ProgramData\Anaconda3\lib\site-packages\speech_recognition\__init__.py", line 657, in listen
    buffer = source.stream.read(source.CHUNK)
  File "C:\ProgramData\Anaconda3\lib\site-packages\speech_recognition\__init__.py", line 198, in read
    return self.pyaudio_stream.read(size, exception_on_overflow=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
OSError: [Errno -9988] Stream closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "write_audio.py", line 11, in <module>
    audio = r.listen(source)
  File "C:\ProgramData\Anaconda3\lib\site-packages\speech_recognition\__init__.py", line 188, in __exit__
    self.stream.close()
  File "C:\ProgramData\Anaconda3\lib\site-packages\speech_recognition\__init__.py", line 203, in close
    if not self.pyaudio_stream.is_stopped():
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyaudio.py", line 543, in is_stopped
    return pa.is_stream_stopped(self._stream)
OSError: [Errno -9988] Stream closed

Expected behaviour
------------------

It Should record the information and store it in some format.

Actual behaviour
----------------

Its throwing an error saying that stream is closed

Traceback (most recent call last):
  File "write_audio.py", line 11, in <module>
    audio = r.listen(source)
  File "C:\ProgramData\Anaconda3\lib\site-packages\speech_recognition\__init__.py", line 657, in listen
    buffer = source.stream.read(source.CHUNK)
  File "C:\ProgramData\Anaconda3\lib\site-packages\speech_recognition\__init__.py", line 198, in read
    return self.pyaudio_stream.read(size, exception_on_overflow=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
OSError: [Errno -9988] Stream closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "write_audio.py", line 11, in <module>
    audio = r.listen(source)
  File "C:\ProgramData\Anaconda3\lib\site-packages\speech_recognition\__init__.py", line 188, in __exit__
    self.stream.close()
  File "C:\ProgramData\Anaconda3\lib\site-packages\speech_recognition\__init__.py", line 203, in close
    if not self.pyaudio_stream.is_stopped():
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyaudio.py", line 543, in is_stopped
    return pa.is_stream_stopped(self._stream)
OSError: [Errno -9988] Stream closed

System information
------------------

(Delete all the statements that don't apply.)

My System in windows 7 64

My **Python version** is Python 3.6.1 :: Anaconda 4.4.0 (64-bit)

My **Pip version** is pip 9.0.1 from C:\ProgramData\Anaconda3\lib\site-packages (python 3.6)

My **SpeechRecognition library version** is 3.8.1

My **PyAudio library version** is 0.2.11

My **microphones** are: ['Microsoft Sound Mapper - Input', 'Microphone (Realtek High Defini', 'Microsoft Sound Mapper - Output', 'Speaker/HP (Realtek High Defini']

My **working microphones** are: {0: 'Microsoft Sound Mapper - Input', 1: 'Microphone (Realtek High Defini'}

**Comment by ntpincus** [comment]
Did you determine the source of the issue?
I am also seeing the same error message on Ubuntu from a fresh manual install of the repo

Say something!
Traceback (most recent call last):
  File "SimpleSpeech.py", line 10, in <module>
    audio = r.listen(source)
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 188, in __exit__
    self.stream.close()
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 203, in close
    if not self.pyaudio_stream.is_stopped():
  File "build/bdist.linux-x86_64/egg/pyaudio.py", line 543, in is_stopped
IOError: [Errno -9988] Stream closed

I am seeing this error on a fresh clone of the repo (I'm using Ubuntu 14.04 x86_64), after running python setup.py install
However, I do not see this error when I do a pip install
``

**Comment by mnkarbhasgi** [comment]
I am also getting the same error
    audio = r.listen(source)
  File "C:\Users\mnkar\Miniconda3\envs\dummy\lib\site-packages\speech_recognition\__init__.py", line 151, in __exit__
    self.stream.close()
  File "C:\Users\mnkar\Miniconda3\envs\dummy\lib\site-packages\speech_recognition\__init__.py", line 166, in close
    if not self.pyaudio_stream.is_stopped():
  File "C:\Users\mnkar\Miniconda3\envs\dummy\lib\site-packages\pyaudio.py", line 543, in is_stopped
    return pa.is_stream_stopped(self._stream)
OSError: [Errno -9988] Stream closed
