### ISSUE TITLE
AttributeError: module 'speech_recognition' has no attribute 'Recognizer'

### ISSUE THREAD

**Issue by code3hr** [Uberi/speech_recognition#313]
Steps to reproduce
------------------

1. (How do you make the issue happen? Does it happen every time you try it?)
2. (Make sure to go into as much detail as needed to reproduce the issue. Posting your code here can help us resolve the problem much faster!)
3. (If there are any files, like audio recordings, don't forget to include them.)

Expected behaviour
------------------

(What did you expect to happen?)

Actual behaviour
----------------

(What happened instead? How is it different from what you expected?)

```
(If the library threw an exception, paste the full stack trace here)
```

System information
------------------

(Delete all the statements that don't apply.)

My **system** is <INSERT SYSTEM HERE>. (For example, "Ubuntu 16.04 LTS x64", "Windows 10 x64", or "macOS Sierra".)

My **Python version** is <INSERT VERSION HERE>. (You can check this by running `python -V`.)

My **Pip version** is <INSERT VERSION HERE>. (You can check this by running `pip -V`.)

My **SpeechRecognition library version** is <INSERT VERSION HERE>. (You can check this by running `python -c "import speech_recognition as sr;print(sr.__version__)"`.)

My **PyAudio library version** is <INSERT VERSION HERE> / I don't have PyAudio installed. (You can check this by running `python -c "import pyaudio as p;print(p.__version__)"`.)

My **microphones** are: (You can check this by running `python -c "import speech_recognition as sr;print(sr.Microphone.list_microphone_names())"`.)

My **working microphones** are: (You can check this by running `python -c "import speech_recognition as sr;print(sr.Microphone.list_working_microphones())"`.)

I **installed PocketSphinx from** <INSERT SOURCE HERE>. (For example, from the Debian repositories, from Homebrew, or from the source code.)

**Comment by svsashank** [comment]
Check the name of your python file name. That fixed my error.

**Comment by senihtosun** [comment]
What do u mean by python file name?

**Comment by rderua** [comment]
@senihtosun maybe you named your working file as the function your looking for inside the r object.
So in that case you'll need to change that as different one

**Comment by tajalagawani** [comment]
Your name of the file is speech_recognition.py and python is looking not to the speech_recognition module but search the Recognizer in your module (file).

You need simple to rename your module (file).

For example from speech_recognition.py to sp_recog.py

**Comment by satbecse** [comment]
Thank you. It worked for me as well after renaming the file.

**Comment by rakeshpatil993** [comment]
cat s2t.py
#Python 2.x program to transcribe an Audio file
import speech_recognition as sr

AUDIO_FILE = ("/home/rakeshpatil993/OSR_us_000_0010_8k.wav")

# use the audio file as the audio source

r = sr.Recognizer()

with sr.AudioFile(AUDIO_FILE) as source:
    #reads the audio file. Here we use record instead of
    #listen
    audio = r.record(source)

try:
    print("The audio file contains: " + r.recognize_google(audio))

except sr.UnknownValueError:
    print("Google Speech Recognition could not understand audio")

except sr.RequestError as e:
    print("Could not request results from Google Speech Recognition service; {0}".format(e))
===========================================================
python s2t.py
Traceback (most recent call last):
  File "s2t.py", line 10, in <module>
    with sr.AudioFile(AUDIO_FILE) as source:
AttributeError: 'module' object has no attribute 'AudioFile'

getting above error while converting speech to text using speech_recognition . i have installed beloa packages, then also facing the issues.

pip install SpeechRecognition

pip install pyaudio

**Comment by yashpalsinha** [comment]
PS G:\program files> python -u "g:\program files\speech1.py"
Traceback (most recent call last):
  File "g:\program files\speech1.py", line 3, in <module>
    with sr.microphone() as source:
AttributeError: module 'speech_recognition' has no attribute 'microphone'
PS G:\program files> 

same problem facing how to fix this

**Comment by Anshifa** [comment]
@rakeshpatil993 same issue

**Comment by MuditaB** [comment]
I am also facing the same problem. 


AttributeError: 'Recognizer' object has no attribute 'AudioFile'

I am running the code in googlecolab, with ipynb name as sp_recog.ipynb
