### ISSUE TITLE
AttributeError: Could not find PyAudio; check installation Raspberry Pi 3

### ISSUE THREAD

**Issue by aaroncheung123** [Uberi/speech_recognition#326]
I am currently trying to get speech recognition to work on my raspberry pi 3 however this is the error that I am getting.

`Traceback (most recent call last):
  File "listen.py", line 8, in <module>
    with sr.Microphone() as source:
  File "/home/pi/Documents/Test/env/local/lib/python2.7/site-packages/speech_recognition/__init__.py", line 79, in __init__
    self.pyaudio_module = self.get_pyaudio()
  File "/home/pi/Documents/Test/env/local/lib/python2.7/site-packages/speech_recognition/__init__.py", line 110, in get_pyaudio
    raise AttributeError("Could not find PyAudio; check installation")
AttributeError: Could not find PyAudio; check installation
`

My issue is almost exactly the same as sanster9292 who opened a ticket on June 2, 2017.  I tried everything that you asked him to; however, I am still getting the error above.  Please, let me know if you need more information.  Do you have any idea how to get this to work on my raspberry pi 3?

**Comment by jhoelzl** [comment]
Try in terminal in your project / virtual environment:
```

python -i
import pyaudio
```
Do you also get an error?

**Comment by aaroncheung123** [comment]
Yes I do.  Below is the error I got.

`>>> import pyaudio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pyaudio
`

**Comment by jhoelzl** [comment]
Okay, then please install [pyaudio](http://people.csail.mit.edu/hubert/pyaudio/) using:

`pip install pyaudio`

**Comment by aaroncheung123** [comment]
that's my problem.  I have done pip install pyaudio but it is still giving me that error.

**Comment by jhoelzl** [comment]
Do you get an error when installing pyaudio?

**Comment by aaroncheung123** [comment]
No, I don't think so.

**Comment by aaroncheung123** [comment]
When I ran the pip install again this is what it says.

`Collecting pyaudio
  Using cached PyAudio-0.2.11.tar.gz
Building wheels for collected packages: pyaudio
  Running setup.py bdist_wheel for pyaudio ... done
  Stored in directory: /home/pi/.cache/pip/wheels/8d/b4/65/042bc5f996556eb8cdbeaad786f7991dfab8ef6118d58ddbee
Successfully built pyaudio
Installing collected packages: pyaudio
Successfully installed pyaudio-0.2.11
`

**Comment by aaroncheung123** [comment]
When I run this code 
`import speech_recognition as sr

r = sr.Recognizer()
with sr.Microphone() as source:
    print("Waiting to be called on")
    audio = r.listen(source)
try:
    #print(r.recognize_google(audio))

    if "hey buddy" in r.recognize_google(audio):
        print('Yay')

except sr.UnknownValueError:
    print("Could not understand audio")
except sr.RequestError as e:
    print("Could not request results; {0}".format(e))`

This is the error I receive.

`ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
connect(2) call to /tmp/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Waiting to be called on
`

When I speak into the microphone it just doesn't work.  I know the microphone is working too.

**Comment by WhiteDevil02** [comment]
dear sir my error is same import pyaudio

please help me

**Comment by ScrappyCocoJamba** [comment]
hello guys, I have some problem too

anyone solved this problem?

ubuntu 19.10

**Comment by sourabh-st** [comment]
i got this problem while installing pyaudio.

![Screenshot 2020-05-07 at 11 05 50 AM](https://user-images.githubusercontent.com/64778799/81258791-1d36ba80-9054-11ea-8a26-183ca598f98d.png)

**Comment by sandesh2526** [comment]
> i got this problem while installing pyaudio.
> 
> ![Screenshot 2020-05-07 at 11 05 50 AM](https://user-images.githubusercontent.com/64778799/81258791-1d36ba80-9054-11ea-8a26-183ca598f98d.png)
> 

I got same problem while installing it on pydroid...if it appears on windows you can fix it using 
pip install pipwin
pipwin install pyaudio

**Comment by ritujashinde97** [comment]
> pip install pipwin
> pipwin install pyaudio

It worked for me (windows)

**Comment by Jayant-tembhurkar** [comment]
Not working

**Comment by maannsaayyy** [comment]
yes its not working for me either (Windows) although i updated python

**Comment by sandesh2526** [comment]
What error it shows?

**Comment by maannsaayyy** [comment]
This

**Comment by sandesh2526** [comment]
> pip install pipwin
> pipwin install pyaudio

After executing this commands what it shows?

**Comment by maannsaayyy** [comment]
It shows that pipwin is external and is non recognised I tried

**Comment by maannsaayyy** [comment]
-

**Comment by sandesh2526** [comment]
Can you share a screenshot of error...?

**Comment by maannsaayyy** [comment]
pipwin error

**Comment by sandesh2526** [comment]
What are you using IDE or command prompt?

**Comment by maannsaayyy** [comment]
cmd also im using windows

**Comment by sandesh2526** [comment]
This might work-
 **install PyAudio‑0.2.11‑cp37‑cp37m‑win_amd64.whl**

**Comment by maannsaayyy** [comment]
not working

**Comment by Jayant-tembhurkar** [comment]
Use python version 3.6 not above than that

**Comment by maannsaayyy** [comment]
But why is this issue happening in latest version of python?

**Comment by Sudarshan-17** [comment]
> > i got this problem while installing pyaudio.
> > ![Screenshot 2020-05-07 at 11 05 50 AM](https://user-images.githubusercontent.com/64778799/81258791-1d36ba80-9054-11ea-8a26-183ca598f98d.png)
> 
> I got same problem while installing it on pydroid...if it appears on windows you can fix it using
> pip install pipwin
> pipwin install pyaudio

Not working .....

**Comment by jit01** [comment]
When It comes to listing part it was saying 

```ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave```

and code was 
 with sr.Microphone() as source:
        print("Listening")
        audio = re.listen(source)


I solved this problem by simply changing the listen() parameter, and installed some pkg 

sudo apt-get install portaudio19-dev 
sudo apt-get install portaudio19-dev python-all-dev python3-all-dev && sudo pip install pyaudio
pip install pyaudio

with sr.Microphone() as source:
        print("Listening")
        audio = re.listen(source, timeout=3, phrase_time_limit=3)

**Comment by elvinaqa** [comment]
first
pip install pipwin
then
pipwin install pyaudio

**Comment by parthgandhi487** [comment]
I installed pip install pipwin and then when i tried installing pipwin install pyaudio, it is showing syntax error as below :  

 File "<ipython-input-9-a29514d3d9ba>", line 1
    pip install pipwin
              ^
SyntaxError: invalid syntax

**Comment by parthgandhi487** [comment]
Please help me on this

**Comment by gursevakgill2300** [comment]
pip install pipwin
pipwin install PyAudio
Try this ommand in cmd not in any IDE

**Comment by TuHechiceroFavorito** [comment]
I'm using Linux and for me this command on terminal worked:

sudo apt install python3-pyaudio

**Comment by Im-Fran** [comment]
If someone still having this issue after installing python3-pyaudio this is how I solved it:

1. Execute this: `sudo apt-get install portaudio19-dev python3-pyaudio`
2. Now install pyaudio through pip: `pip install pyaudio`
3. Now you should be able to use pyaudio!

This is for linux, tested in popOS (should work in ubuntu and other linux distrubtions too)
