### ISSUE TITLE
NotImplementedError: this is an abstract class

### ISSUE THREAD

**Issue by harris7** [Uberi/speech_recognition#384]
The current code is as follows:

`import speech_recognition as sr
r = sr.Recognizer()

def callback(r, audio):
    try:
        print("You said " + r.recognize(audio))
    except LookupError:
        print("Oops! Didn't catch that")
r.listen_in_background(r, callback)

import time
while True:
    time.sleep(0.1)
`
It is currently raising the error:

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Oliver\Documents\Python\Modern python\lib\threading.py", line 921, in _bootstrap_inner
    self.run()
  File "C:\Users\Oliver\Documents\Python\Modern python\lib\threading.py", line 869, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Oliver\Documents\Python\Modern python\lib\site-packages\speech_recognition\__init__.py", line 690, in threaded_listen
    with source as s:
  File "C:\Users\Oliver\Documents\Python\Modern python\lib\site-packages\speech_recognition\__init__.py", line 51, in __enter__
    raise NotImplementedError("this is an abstract class")
NotImplementedError: this is an abstract class`

I am attempting to make my own hotword detection program which would need the speech recognizer to actively recognize speech and convert it into text while the recognizer instance is still running (without stopping)

**Comment by harris7** [comment]
Snowboy hotword detection is not a viable option because I am running windows

**Comment by palikar** [comment]
Hi @harris7,

please refer to the examples folder for the proper use of listening on the background. There you can find [sample code](https://github.com/Uberi/speech_recognition/blob/master/examples/background_listening.py) with explanations.
