### ISSUE TITLE
IBM iam_apikey

### ISSUE THREAD

**Issue by PaulFH** [Uberi/speech_recognition#413]
Steps to reproduce
------------------

1. (How do you make the issue happen? Does it happen every time you try it?)
I would like to use IBM instead of Google. In the word game example, replaced line 43 with response["transcription"] = recognizer.recognize_ibm(audio).

In the documentation: recognizer_instance.recognize_ibm(audio_data: AudioData, username: str, password: str, language: str = "en-US", show_all: bool = False) -> Union[str, Dict[str, Any]]

IBM moved to IAM_APIKEY, away from username / password

2. (Make sure to go into as much detail as needed to reproduce the issue. Posting your code here can help us resolve the problem much faster!)

    # set up the response object
    response = {
        "success": True,
        "error": None,
        "transcription": None
    }

    # try recognizing the speech in the recording
    # if a RequestError or UnknownValueError exception is caught,
    #     update the response object accordingly
    try:
        #PH: replacing with IBM response["transcription"] = recognizer.recognize_google(audio)
        response["transcription"] = recognizer.recognize_ibm(audio, iam_apikey='*********',
        url='https://stream.watsonplatform.net/speech-to-text/api')

3. (If there are any files, like audio recordings, don't forget to include them.)

Expected behaviour
------------------
Would like to leverage IBM since it provides intermediate results, much faster as Google

Actual behaviour
----------------
Error:
Traceback (most recent call last):
  File "wordGuess.py", line 92, in <module>
    guess = recognize_speech_from_mic(recognizer, microphone)
  File "wordGuess.py", line 45, in recognize_speech_from_mic
    url='https://stream.watsonplatform.net/speech-to-text/api')
TypeError: recognize_ibm() got an unexpected keyword argument 'iam_apikey'
(What happened instead? How is it different from what you expected?)

```
(If the library threw an exception, paste the full stack trace here)
```

System information
------------------

(Delete all the statements that don't apply.)

My **system** is macOS Mojave
My **Python version** is 3.7.2
My **Pip version** is 19.0.3
My **SpeechRecognition library version** is 3.8.1
My **PyAudio library version** is 0.2.11
My **microphones** are: MacBook Pro Microphone', 'MacBook Pro Speakers', 'Soundflower (2ch)', 'Soundflower (16ch)']

**Comment by yianchen** [comment]
I am trying to use IBM API as well. Tried to follow the steps above but got some questions.

> replaced line 43 with response["transcription"] = recognizer.recognize_ibm(audio).

which line of code in `audio_transcribe.py` did you refer to? 

Also, when you said 

> In the documentation: recognizer_instance.recognize_ibm(audio_data: AudioData, username: str, password: str, language: str = "en-US", show_all: bool = False) -> Union[str, Dict[str, Any]]

Did you refer to `__init__.py`?

> File "wordGuess.py", line 92, in
guess = recognize_speech_from_mic(recognizer, microphone)

Where did the `wordGuess.py` file come from?

Thanks!

**Comment by kavyabgowda** [comment]
Even I'm facing the same issue while trying to convert the audio files to text using recognize_ibm(). This is my code snippet.


authenticator = IAMAuthenticator('{api-secret}') 
speech_to_text = SpeechToTextV1(
    authenticator=authenticator
)

speech_to_text.set_service_url('{api_url}')


r=sr.Recognizer();
audio='file_compressed.wav'
with sr.AudioFile(audio) as source:
    sound=r.listen(source)
try:
    
    speech_to_text.recognize(sound)
  
except ApiException as ex:
    print("Method failed with status code " + str(ex.code) + ": " + ex.message)

I'm getting following error:
'AudioData' object is not iterable.
