### ISSUE TITLE
OSError: [Error -9998] Invalid no. of channels

### ISSUE THREAD

**Issue by JayjeetAtGithub** [Uberi/speech_recognition#444]
I am getting this error while doing speech recognition using USB-Microphone in Raspberry Pi 3.

```
Expression 'parameters->channelCount <= maxChans' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1514
Expression 'ValidateParameters( inputParameters, hostApi, StreamDirection_In )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2818
Traceback (most recent call last):
  File "/home/pi/AT-Software-v3/sse.py", line 51, in <module>
    start_voice_recognition()
  File "/home/pi/AT-Software-v3/sse.py", line 46, in start_voice_recognition
    with m as source:
  File "/home/pi/venv/lib/python3.5/site-packages/speech_recognition/__init__.py", line 141, in __enter__
    input=True,  # stream is an input stream
  File "/home/pi/venv/lib/python3.5/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/home/pi/venv/lib/python3.5/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9998] Invalid number of channels
```

**Comment by tobinrivera** [comment]
I'm having the exact same issue

**Comment by davidscottconrad** [comment]
same issue
