### ISSUE TITLE
'Recognizer' object has no attribute 'recognize_tensorflow'

### ISSUE THREAD

**Issue by Mattia541993** [Uberi/speech_recognition#455]
Steps to reproduce
------------------
I saw in the examples section the following [one]:(https://github.com/Uberi/speech_recognition/blob/master/examples/tensorflow_commands.py)
where tensor-flow method of Recognizer is used. (example in master branch)
I jumped to definition of the `recognize_tensorflow` function and I saw that it's not on a specific branch, but on a tree c8985... in the `__init__.py` file. Indeed if I call `dir(r)` where `r` is an instance of `Recognizer` class, `recognize_tensorflow` method doesn't exists. 
Is it a suitable commit I can use for testing? Because I saw It that the commit with `recognize_tensorflow` method has been edited on 19th may 2019 and the master branch on 20th December 2018 and even in the documentation and on the Pypi page I can't find any reference of this type or recognizer.

System information
------------------
My **system** is macOS Catalina 10.15.2
My **Python version** is 3.7.5
My **Pip version** is 19.3.1
My **SpeechRecognition library version** is 3.8.1

Thank you,
Mattia

**Comment by UmutAlihan** [comment]
same issue here
I get the error message below:
AttributeError: 'Recognizer' object has no attribute 'recognize_tensorflow'

**Comment by infacc** [comment]
I ran into a similar issue where the TensorFlow version was the problem. Although I can't recreate this issue, it may help to downgrade to TensorFlow 1. My 'dirty' solution was to replace [this line](https://github.com/Uberi/speech_recognition/blob/8b07762f80dfec2d34fb4c40b8eddbb7ec503521/speech_recognition/__init__.py#L1429) with `import tensorflow.compat.v1 as tf`.


<details>
<summary>Code</summary>

```python
import speech_recognition as sr

speech = sr.Recognizer()
with sr.AudioFile('audio.wav') as source:
    audio = speech.record(source)
    print(speech.recognize_tensorflow(audio))
```
</details>

<details>
<summary>Error</summary>

```
Traceback (most recent call last):
  File "/mnt/e/Temp/hds/get_subs.py", line 6, in <module>
    print(speech.recognize_tensorflow(audio))
  File "/home/user/anaconda3/lib/python3.10/site-packages/speech_recognition/__init__.py", line 1437, in recognize_tensorflow
    with tf.gfile.FastGFile(tensor_graph, 'rb') as f:
AttributeError: module 'tensorflow' has no attribute 'gfile'. Did you mean: 'fill'?
```
</details>
