### ISSUE TITLE
Speech Recognition not working

### ISSUE THREAD

**Issue by Dave234322** [Uberi/speech_recognition#498]
I am trying to use speech recognition on python 3.8 i am fairly new to programming and i have tried multiple solution such as using pip to install pyaudio but it says "Command 'pip' not found but there are 18 similar ones" the code i am using is:

import speech_recognition as sr

# Record Audio
r = sr.Recognizer()
with sr.Microphone() as source:
    print("Say something!")
    audio = r.listen(source)

# Speech recognition using Google Speech Recognition
try:
    # for testing purposes, we're just using the default API key
    # to use another API key, use `r.recognize_google(audio, key="GOOGLE_SPEECH_RECOGNITION_API_KEY")`
    # instead of `r.recognize_google(audio)`
    print("You said: " + r.recognize_google(audio))
except sr.UnknownValueError:
    print("Google Speech Recognition could not understand audio")
except sr.RequestError as e:
    print("Could not request results from Google Speech Recognition service; {0}".format(e))

the error i get is:
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/isaac/.config/JetBrains/PyCharmCE2020.2/scratches/scratch.py", line 5, in <module>
    with sr.Microphone() as source:
  File "/usr/local/lib/python3.8/dist-packages/speech_recognition/__init__.py", line 79, in __init__
    self.pyaudio_module = self.get_pyaudio()
  File "/usr/local/lib/python3.8/dist-packages/speech_recognition/__init__.py", line 110, in get_pyaudio
    raise AttributeError("Could not find PyAudio; check installation")
AttributeError: Could not find PyAudio; check installation

Process finished with exit code 1

I am using Ubuntu 20.04 and using the software pycharm

**Comment by maschmi1** [comment]
@Dave234322 there’s probably configuration in pycharm that you need to do to point to the correct Python installation. Try to run it from the terminal and see if you get the same thing. If you do you probably need to install pip.

For Ubuntu it should just be
```bash
sudo apt install python3-pip
```

**Comment by saiphani1998** [comment]
install pip and later that install pyaudio.
sudo apt install python3-pip
pip3 install pyaudio

**Comment by Teshan-Sachintha** [comment]
Reinstall Python in your compuer .This time tick the check box **_Add Python 3.x to PATH_**(When installs you may have not given it 
![download](https://user-images.githubusercontent.com/73296222/96968972-652c9980-152f-11eb-8c68-aa6f90af4c2d.jpg)
.Sometimes python command doesn't work because of it.)
Then install by using `pip`
`pip install pyaudio`-to install
`pip uninstall pyaudio`-to uninstall

if yhe above install didn't work try - `pip install pipwin` then `pipwin install pyaudio`
