### ISSUE TITLE
AttributeError: module 'speech_recognition' has no attribute 'microphene'

### ISSUE THREAD

**Issue by 3yalzayed** [Uberi/speech_recognition#523]
Hello 

I have a problem on my code. I import (import speech_recognition as sr, from gtts import gTTS, import playsound, import os)
 what I need to do to solve the problem please help me ):
:
Traceback (most recent call last):
  File "/Users/mac/PycharmProjects/AI/main.py", line 36, in <module>
    command = voice_command_processor()
  File "/Users/mac/PycharmProjects/AI/main.py", line 14, in voice_command_processor
    with sr.microphene() as source:
AttributeError: module 'speech_recognition' has no attribute 'microphene'

question quick If I want to apply os.system for windows I use start for Mac what I use
final comment I want to build my own Ai Assistant where the best way I can to it in python or IBM Waston Assistant?

**Comment by Teshan-Sachintha** [comment]
Why are you typed sr.microphone() as sr.microph**e**ne().Check you spellings in the word.And as I read the code I don't find it is good thing to write/run the whole code because you are not installing all the API's mension in the code.So figure out a good API and Write or keep code of that API only.
As example:
I used Google Speech recognition API, windows-(pip install google-api-python-client)

**Comment by Teshan-Sachintha** [comment]
> Why are you typed sr.microphone() as sr.microph**e**ne().Check you spellings in the word.And as I read the code I don't find it is good thing to write/run the whole code because you are not installing all the API's mension in the code.So figure out a good API and Write or keep code of that API only.
> As example:
> I used Google Speech recognition API, windows-(pip install google-api-python-client)
> so keep these line only-

**Comment by amannegi117** [comment]
use pyttsx3 and speech recognition module will surely be of great help

**Comment by amannegi117** [comment]
and there is a spelling mistake you should do sr.Microphone() as source
