### ISSUE TITLE
sr.Microphone - Device Unavailable Error

### ISSUE THREAD

**Issue by rudrathegreat** [Uberi/speech_recognition#524]
Steps to reproduce
------------------
```Python

import speech_recognition as sr

r = sr.Recognizer()

with sr.Microphone() as source:
    print('Say something')
    audio = r.listen(source)
    r.recognize_google(audio)

```

Using Windows 7, Python 3.7.0, Speech_Recognition 3.8.1 and PyAudio 0.2.11

Expected behaviour
------------------

I'm expecting the program to be able to recognise what I am trying to say

Actual behaviour
----------------
```
Traceback (most recent call last):
  File "D:/Directory/Speech_To_Text/test.py", line 5, in <module>
    with sr.Microphone() as source:
  File "C:\Users\testing\AppData\Local\Programs\Python\Python37-32\lib\site-packages\speech_recognition\__init__.py", line 141, in __enter__
    input=True,  # stream is an input stream
  File "C:\Users\testing\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "C:\Users\testing\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

```

System information
------------------

My **system** is Windows 7 x64.

My **Python version** is 3.7.0. 

My **Pip version** is 20.2.3. 

My **SpeechRecognition library version** is 3.8.1.

My **PyAudio library version** is 0.2.11 

My **microphones** are: 

```

['Microsoft Sound Mapper - Input',
 'Microphone Array (Realtek Audio',
 'Headset Microphone (USB Audio D',
 'Stereo Mix (Realtek Audio)',
 'Microsoft Sound Mapper - Output',
 'Headset Earphone (USB Audio Dev',
 'Speakers / Headphones (Realtek ',
 'Primary Sound Capture Driver',
 'Microphone Array (Realtek Audio)',
 'Headset Microphone (USB Audio Device)',
 'Stereo Mix (Realtek Audio)',
 'Primary Sound Driver',
 'Headset Earphone (USB Audio Device)',
 'Speakers / Headphones (Realtek Audio)',
 'Headset Earphone (USB Audio Device)',
 'Speakers / Headphones (Realtek Audio)',
 'Microphone Array (Realtek Audio)',
 'Stereo Mix (Realtek Audio)',
 'Headset Microphone (USB Audio Device)',
 'Speakers (Realtek HD Audio output)',
 'Jack Mic (Realtek HD Audio Front Mic input)',
 'Microphone Array (Realtek HD Audio Mic Array input)',
 'Stereo Mix (Realtek HD Audio Stereo input)',
 'Headset Microphone (USB Audio Device)',
 'Headset Earphone (USB Audio Device)']

```

My **working microphones** are:

```

Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: type object 'Microphone' has no attribute 'list_working_microphones'

```

**Comment by rudrathegreat** [comment]
Fixed (`list_working_microphones` functions was not installed)
