### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hguptaa** [Uberi/speech_recognition#539]
def takecommand():
    # audio input
    r = sr.Recognizer()
    with sr.Microphone() as source:
        print("Listening...")
        r.pause_threshold = 1
        audio = r.listen(source)

    try:
        print("Recognizing...")
        query = r.recognize_google(audio , Language='en-in')
        print(f"User: said: , {query}\n")   
    
    except Exception as e:
        print("say that again plese...")
        return "None"
    return query

**Comment by hguptaa** [comment]
> def takecommand():
> # audio input
> r = sr.Recognizer()
> with sr.Microphone() as source:
> print("Listening...")
> r.pause_threshold = 1
> audio = r.listen(source)
> 
> ```
> try:
>     print("Recognizing...")
>     query = r.recognize_google(audio , Language='en-in')
>     print(f"User: said: , {query}\n")   
> 
> except Exception as e:
>     print("say that again plese...")
>     return "None"
> return query
> ```

Traceback (most recent call last):
  File "e:/python/Darwin.py", line 50, in <module>
    takecommand()
  File "e:/python/Darwin.py", line 32, in takecommand
    with sr.Microphone() as source:
  File "C:\Users\harsh\AppData\Local\Programs\Python\Python37\lib\site-packages\speech_recognition\__init__.py", line 141, in __enter__
    input=True,  # stream is an input stream
  File "C:\Users\harsh\AppData\Local\Programs\Python\Python37\lib\site-packages\pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "C:\Users\harsh\AppData\Local\Programs\Python\Python37\lib\site-packages\pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9999] Unanticipated host error
