### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by Mutant12345** [Uberi/speech_recognition#542]
**This is the code:**

import pyttsx3  # pyttsx is a text to speech module
import datetime  # system date and time module
import \
    speech_recognition as sr  # as sr means we are storing this module in sr variable and can be accessed in program by usin sode sr

engine = pyttsx3.init('sapi5')  # taking inbuilt voices from windows

voices = engine.getProperty('voices')  # getting inbuilt voice property from engine which has the previous code
# print(voices)

# voices[0].id inbuilt male voice change 0 to 1 to another inbuilt voice
engine.setProperty('voice', voices[1].id)  # setting the engine voice to inbuilt voice having 0 index

# print(voices[1].id)

def speak(audio):  # defining function speak with audio as an argument
    engine.say(audio)  # telling engine to speak the string in audio argument
    engine.runAndWait()  # runs the speech and makes it audible

def wishMe():
    hour = int(datetime.datetime.now().hour)  # type casting current time to int v get only hrs
    if hour >= 0 and hour < 12:  # if it is morning within 12 O clock wish GM
        speak("Good Morning!")

    elif hour >= 12 and hour < 18:
        speak("Good afternoon!")
    else:
        speak("good Evening!")

    speak("I am Jarvis... How may I help you")

def takeCommand():
    '''takes microphone input from speaker
    and returns string output '''

    r = sr.Recognizer()  # recognising speaker's speech with the computer microphone
    with sr.Microphone() as source:
        ''' Creates a new ``Microphone`` instance, which represents a physical microphone 
        # on the computer. source word can be used to access this instead of
        typing whole thing bcoz of using "as source" command'''
    print("listening...")  # the msg shown while v r speaking
    r.pause_threshold = 1
    ''' the programme will wait for a second 
      before it considers that i have completed 
      speaking if i take a pause in btwin'''
    audio = r.listen(source)
    '''records our speech when we start speaking and stops when v pause for a second '''
    try:
        print("Recognising...")
        query = r.recognize_google(audio, language='en-in')
        '''recognize_google  is a function which uses google 
         API to recognise ur speech'''
        print(f"user said:{query}\n")
    except Exception as e:  # if it could not recognise u

        # print(e)

        print("Say that again pls")
        # speak("repeat please")
        return "None"  # if any problem return none string
    return query

if __name__ == '__main__':  # main method just type main and click on the option in intellisense

    # speak("Hello Hello")  # calling speak function and setting audio parameter to the string in bracket
    wishMe()  # calling wishme function
    takeCommand()

I am getting Error:
Traceback (most recent call last):
  File "C:\Users\shish\PycharmProjects\pythonProject\jarvis1.py", line 72, in <module>
    takeCommand()
listening...
  File "C:\Users\shish\PycharmProjects\pythonProject\jarvis1.py", line 50, in takeCommand
    audio = r.listen(source)
  File "C:\Users\shish\python1\lib\site-packages\speech_recognition\__init__.py", line 594, in listen
    assert source.stream is not None, "Audio source must be entered before listening, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?"
AssertionError: Audio source must be entered before listening, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?

Process finished with exit code 1

**please help**

The program is expected to print what I speak

**Comment by Naman-12911** [comment]
Hello sir, can I help you in this project. I want to solve this problem please assign me.

**Comment by Pulkit-Py** [comment]
Dear Sir, i also made the same project but my code is working fine you can try it. 
https://github.com/Pulkit-Py/voice_bot

**Comment by Jehuty-ML** [comment]
> Hello sir, can I help you in this project. I want to solve this problem please assign me.

hello. I face the same problem now. Could you please tell me hot to fixed it?

**Comment by Jehuty-ML** [comment]
> > Hello sir, can I help you in this project. I want to solve this problem please assign me.
> 
> hello. I face the same problem now. Could you please tell me hot to fixed it?

There is no problem on my pc windows wsl (ubuntu 22.04LTS). But i encounter this problem in my rasberry pi 4 (ubuntu 22.04LTS)
