### ISSUE TITLE
Another speech_recognition.UnknownValueError

### ISSUE THREAD

**Issue by csarami** [Uberi/speech_recognition#560]
Hi,

I am running the code below in Python 3.7.6 64-bit on Latest macOS Mojave.

```
import speech_recognition as sr
r = sr.Recognizer()
mic = sr.Microphone()
with mic as source:
    r.adjust_for_ambient_noise(source)
    audio = r.listen(source)
    transcript = r.recognize_google(audio)
    print(transcript)
```

But I get the error below:

```
Traceback (most recent call last):
  File "trascribe.py", line 7, in <module>
    transcript = r.recognize_google(audio)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/speech_recognition/__init__.py", line 858, in recognize_google
    if not isinstance(actual_result, dict) or len(actual_result.get("alternative", [])) == 0: raise UnknownValueError()
speech_recognition.UnknownValueError
```
What is wrong, please?

**Comment by kr-prince** [comment]
Refer this open issue https://github.com/Uberi/speech_recognition/issues/383

**Comment by csarami** [comment]
Thank you.
