### ISSUE TITLE
ERROR!!! BUT WHY?

### ISSUE THREAD

**Issue by Pyton-Projects** [Uberi/speech_recognition#569]
Traceback (most recent call last):
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\site-packages\speech_recognition\__init__.py", line 203, in __enter__
    self.audio_reader = wave.open(self.filename_or_fileobject, "rb")
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\wave.py", line 510, in open
    return Wave_read(f)
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\wave.py", line 164, in __init__
    self.initfp(f)
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\wave.py", line 131, in initfp
    raise Error('file does not start with RIFF id')
wave.Error: file does not start with RIFF id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\site-packages\speech_recognition\__init__.py", line 208, in __enter__
    self.audio_reader = aifc.open(self.filename_or_fileobject, "rb")
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\aifc.py", line 917, in open
    return Aifc_read(f)
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\aifc.py", line 352, in __init__
    self.initfp(file_object)
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\aifc.py", line 316, in initfp
    raise Error('file does not start with FORM id')
aifc.Error: file does not start with FORM id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\site-packages\speech_recognition\__init__.py", line 234, in __enter__
    self.audio_reader = aifc.open(aiff_file, "rb")
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\aifc.py", line 917, in open
    return Aifc_read(f)
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\aifc.py", line 358, in __init__
    self.initfp(f)
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\aifc.py", line 314, in initfp
    chunk = Chunk(file)
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\chunk.py", line 63, in __init__
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\projects\Music Player Using Tkinter!\Music_Player.py", line 76, in <module>
    with sr.AudioFile(filename) as source:
  File "C:\Users\pooop\AppData\Local\Programs\Python\Python38-32\lib\site-packages\speech_recognition\__init__.py", line 236, in __enter__
    raise ValueError("Audio file could not be read as PCM WAV, AIFF/AIFF-C, or Native FLAC; check if file is corrupted or in another format")
ValueError: Audio file could not be read as PCM WAV, AIFF/AIFF-C, or Native FLAC; check if file is corrupted or in another format
------------------------------------------------------------------------------------------------
WHY THE ERROR OCCURS! TELL ME WHY????

**Comment by Pyton-Projects** [comment]
Mistake
