### ISSUE TITLE
speech_recognition.RequestError: recognition request failed: Bad Request

### ISSUE THREAD

**Issue by DanielLim7** [Uberi/speech_recognition#575]
Steps to reproduce
------------------

1. (How do you make the issue happen? Does it happen every time you try it?)
It happens every time I run.
2. (Make sure to go into as much detail as needed to reproduce the issue. Posting your code here can help us resolve the problem much faster!)
My code was working a few weeks ago. Suddenly, I was getting an error about a bad request. I thought of what I have done and I remember I exported the python path. I was wondering if this could cause the problem. Right now, I am using a virtual environment to run the code.
My code is below.
```
import speech_recognition as sr

r = sr.Recognizer()

with sr.Microphone() as source:
    print('say something')
    audio = r.listen(source)
    voice_data = r.recognize_google(audio)
    print(voice_data)
```
3. (If there are any files, like audio recordings, don't forget to include them.)

Expected behavior
------------------
(What did you expect to happen?)
I am expected to transcribe my voice into text.

Actual behavior
----------------
```
Traceback (most recent call last):
  File "/research/venv/lib/python3.9/site-packages/speech_recognition/__init__.py", line 840, in recognize_google
    response = urlopen(request, timeout=self.operation_timeout)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/research/main.py", line 8, in <module>
    voice_data = r.recognize_google(audio)
  File "/venv/lib/python3.9/site-packages/speech_recognition/__init__.py", line 842, in recognize_google
    raise RequestError("recognition request failed: {}".format(e.reason))
speech_recognition.RequestError: recognition request failed: Bad Request
```
(What happened instead? How is it different from what you expected?)

```
(If the library threw an exception, paste the full stack trace here)
```

System information
------------------

(Delete all the statements that don't apply.)

My **system** is macOS big sur. (For example, "Ubuntu 16.04 LTS x64", "Windows 10 x64", or "macOS Sierra".)

My **Python version** is Python 3.9.6. (You can check this by running `python -V`.)

My **Pip version** is pip 21.1.3. (You can check this by running `pip -V`.)

My **SpeechRecognition library version** is 3.8.1. (You can check this by running `python -c "import speech_recognition as sr;print(sr.__version__)"`.)

My **PyAudio library version** is 0.2.11. (You can check this by running `python -c "import pyaudio as p;print(p.__version__)"`.)

My **microphones** are: ['MacBook Pro Microphone', 'MacBook Pro Speakers'] (You can check this by running `python -c "import speech_recognition as sr;print(sr.Microphone.list_microphone_names())"`.)

My **working microphones** are: I am getting an error when I run the command: AttributeError: type object 'Microphone' has no attribute 'list_working_microphones'

I **installed PocketSphinx from** Homebrew. (For example, from the Debian repositories, from Homebrew, or from the source code.)

**Comment by Cabn32** [comment]
> install pyaudio to fix this error


i also m facing this error, and i have pyaudio installed. @DanielLim7 could you tell me if you have found a way to resolve this issue, it would be of great help me to me.

**Comment by miguellgramacho96** [comment]
same problem

**Comment by AbhijeetJK** [comment]
Used language parameter in recognize_google()
voice_data = r.recognize_google(audio,language='en-in')

**Comment by GayatriDunakhe** [comment]
I have also same error

**Comment by CataBesliu** [comment]
did you find the solution for this?

**Comment by DragonflyRobotics** [comment]
I am also having the same issue. I, too, have PyAudio installed.

**Comment by githubslinechu** [comment]
There is a limit of 10 MB on all single requests sent to the API using local files. In the case of the Recognize and LongRunningRecognize methods, this limit applies to the size of the request sent. In the case of the StreamingRecognize method, the 10 MB limit applies to both the initial StreamingRecognize request and the size of each individual message in the stream. Exceeding this limit will throw an error.

**Comment by githubslinechu** [comment]
by stackoverfloww

**Comment by ldahual** [comment]
> There is a limit of 10 MB on all single requests sent to the API using local files. In the case of the Recognize and LongRunningRecognize methods, this limit applies to the size of the request sent. In the case of the StreamingRecognize method, the 10 MB limit applies to both the initial StreamingRecognize request and the size of each individual message in the stream. Exceeding this limit will throw an error.

I cut wav file into smaller parts and it works

**Comment by nilsplum** [comment]
Consider checking out the MIDI Settings of your Laptop. In macOS this Error is reproducible with the Format "96.000 Hz" in the MIDI Application (which every Macbook has) under the device "Macbook Microphone"
