### ISSUE TITLE
autopy install error

### ISSUE THREAD

**Issue by ssk1504** [Uberi/speech_recognition#579]
Steps to reproduce
------------------
pip install autopy
1. (How do you make the issue happen? Does it happen every time you try it?)
2. (Make sure to go into as much detail as needed to reproduce the issue. Posting your code here can help us resolve the problem much faster!)
3. (If there are any files, like audio recordings, don't forget to include them.)

Expected behaviour
------------------

(What did you expect to happen?)

Actual behaviour
--Collecting autopy
  Using cached autopy-4.0.0.tar.gz (20 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\saikrishna\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Saikrishna\\AppData\\Local\\Temp\\pip-install-5ubivpei\\autopy_fe334aa2623a4f53b7c6c0b7f58271eb\\setup.py'"'"'; __file__='"'"'C:\\Users\\Saikrishna\\AppData\\Local\\Temp\\pip-install-5ubivpei\\autopy_fe334aa2623a4f53b7c6c0b7f58271eb\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Saikrishna\AppData\Local\Temp\pip-pip-egg-info-_d3ps1wa'
         cwd: C:\Users\Saikrishna\AppData\Local\Temp\pip-install-5ubivpei\autopy_fe334aa2623a4f53b7c6c0b7f58271eb\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Saikrishna\AppData\Local\Temp\pip-install-5ubivpei\autopy_fe334aa2623a4f53b7c6c0b7f58271eb\setup.py", line 8, in <module>
        from setuptools_rust import Binding, RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/3d/3e/e589bfe03c7ee1c3d832dda10b908557f25a09d66acfc8fc7d982ee23d1a/autopy-4.0.0.tar.gz#sha256=b889dc1245426aa06769d3d87df0d96904ca729d0e9441a0096aa3ae9fbae43f (from https://pypi.org/simple/autopy/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached autopy-3.1.0.tar.gz (20 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\saikrishna\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Saikrishna\\AppData\\Local\\Temp\\pip-install-5ubivpei\\autopy_004d2d22e9c84c0fb1044e3b4ddde7ed\\setup.py'"'"'; __file__='"'"'C:\\Users\\Saikrishna\\AppData\\Local\\Temp\\pip-install-5ubivpei\\autopy_004d2d22e9c84c0fb1044e3b4ddde7ed\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Saikrishna\AppData\Local\Temp\pip-pip-egg-info-opqtzaby'
         cwd: C:\Users\Saikrishna\AppData\Local\Temp\pip-install-5ubivpei\autopy_004d2d22e9c84c0fb1044e3b4ddde7ed\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Saikrishna\AppData\Local\Temp\pip-install-5ubivpei\autopy_004d2d22e9c84c0fb1044e3b4ddde7ed\setup.py", line 8, in <module>
        from setuptools_rust import Binding, RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/54/64/3a2ccf5540e7f68b70f48978b97d5930caacdc15ec200dd1e7d1dced1371/autopy-3.1.0.tar.gz#sha256=87dceb231051074af50eae7f82d39ecd2a39201e407af1dc00810eb4effeff86 (from https://pypi.org/simple/autopy/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached autopy-3.0.1.tar.gz (18 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\saikrishna\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Saikrishna\\AppData\\Local\\Temp\\pip-install-5ubivpei\\autopy_3cd264273e05439b9703df01569b2594\\setup.py'"'"'; __file__='"'"'C:\\Users\\Saikrishna\\AppData\\Local\\Temp\\pip-install-5ubivpei\\autopy_3cd264273e05439b9703df01569b2594\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Saikrishna\AppData\Local\Temp\pip-pip-egg-info-595o4r0a'
         cwd: C:\Users\Saikrishna\AppData\Local\Temp\pip-install-5ubivpei\autopy_3cd264273e05439b9703df01569b2594\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Saikrishna\AppData\Local\Temp\pip-install-5ubivpei\autopy_3cd264273e05439b9703df01569b2594\setup.py", line 8, in <module>
        from setuptools_rust import Binding, RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2e/ce/ba0b13eaeb479f7fd3b4971252b713f180f03ad5c0f494e5890398f57c92/autopy-3.0.1.tar.gz#sha256=1afa5b214d2ed7782cc8f0f26570c521a828f7a3b03c7cbb86664b8e1dd1a149 (from https://pypi.org/simple/autopy/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached autopy-3.0.0.tar.gz (17 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\saikrishna\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Saikrishna\\AppData\\Local\\Temp\\pip-install-5ubivpei\\autopy_f8e95f7e26594f99a54ffeed95a425d4\\setup.py'"'"'; __file__='"'"'C:\\Users\\Saikrishna\\AppData\\Local\\Temp\\pip-install-5ubivpei\\autopy_f8e95f7e26594f99a54ffeed95a425d4\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Saikrishna\AppData\Local\Temp\pip-pip-egg-info-sgz0l6ef'
         cwd: C:\Users\Saikrishna\AppData\Local\Temp\pip-install-5ubivpei\autopy_f8e95f7e26594f99a54ffeed95a425d4\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Saikrishna\AppData\Local\Temp\pip-install-5ubivpei\autopy_f8e95f7e26594f99a54ffeed95a425d4\setup.py", line 8, in <module>
        from setuptools_rust import Binding, RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d8/6d/bbc9381ef2e674bf512e6988c169a348d19f23d0038c7004ca4238e6712e/autopy-3.0.0.tar.gz#sha256=ba477ae051bf2de6a713b7b96aabb19e82cedaad42784172793c770f62b58051 (from https://pypi.org/simple/autopy/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached autopy-2.1.0.tar.gz (17 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\saikrishna\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Saikrishna\\AppData\\Local\\Temp\\pip-install-5ubivpei\\autopy_3db5d67a6bcb45c49c9541f51dad6521\\setup.py'"'"'; __file__='"'"'C:\\Users\\Saikrishna\\AppData\\Local\\Temp\\pip-install-5ubivpei\\autopy_3db5d67a6bcb45c49c9541f51dad6521\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Saikrishna\AppData\Local\Temp\pip-pip-egg-info-i0ayyy_f'
         cwd: C:\Users\Saikrishna\AppData\Local\Temp\pip-install-5ubivpei\autopy_3db5d67a6bcb45c49c9541f51dad6521\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Saikrishna\AppData\Local\Temp\pip-install-5ubivpei\autopy_3db5d67a6bcb45c49c9541f51dad6521\setup.py", line 8, in <module>
        from setuptools_rust import Binding, RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/31/7a/9bf91734be4ef082d551e3c5ae95e0d44a3f93e585ab93bdf4c2f7e54325/autopy-2.1.0.tar.gz#sha256=ccfe9a44699d05bca7cfe38f088a024b2ded77b64cbe42a62769d05d744c4f22 (from https://pypi.org/simple/autopy/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached autopy-2.0.0.tar.gz (16 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\saikrishna\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Saikrishna\\AppData\\Local\\Temp\\pip-install-5ubivpei\\autopy_10016cc9a3c149b5a252fa643b7d4e2a\\setup.py'"'"'; __file__='"'"'C:\\Users\\Saikrishna\\AppData\\Local\\Temp\\pip-install-5ubivpei\\autopy_10016cc9a3c149b5a252fa643b7d4e2a\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Saikrishna\AppData\Local\Temp\pip-pip-egg-info-5bnmicjo'
         cwd: C:\Users\Saikrishna\AppData\Local\Temp\pip-install-5ubivpei\autopy_10016cc9a3c149b5a252fa643b7d4e2a\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Saikrishna\AppData\Local\Temp\pip-install-5ubivpei\autopy_10016cc9a3c149b5a252fa643b7d4e2a\setup.py", line 8, in <module>
        from setuptools_rust import Binding, RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/40/7f/05acd745ebac3a826f8c53e41c7f945353c685c1dc9cfe9563d350b4a8fc/autopy-2.0.0.tar.gz#sha256=90bb61d9cf705e97d49792ecb7714ba5d7f6b655d9a1bd690d683c91a19b96a2 (from https://pypi.org/simple/autopy/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached autopy-1.1.1.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\saikrishna\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Saikrishna\\AppData\\Local\\Temp\\pip-install-5ubivpei\\autopy_7e1ad0be51014a269e1b67ffbe2e7e98\\setup.py'"'"'; __file__='"'"'C:\\Users\\Saikrishna\\AppData\\Local\\Temp\\pip-install-5ubivpei\\autopy_7e1ad0be51014a269e1b67ffbe2e7e98\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Saikrishna\AppData\Local\Temp\pip-pip-egg-info-d8r0gs7l'
         cwd: C:\Users\Saikrishna\AppData\Local\Temp\pip-install-5ubivpei\autopy_7e1ad0be51014a269e1b67ffbe2e7e98\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Saikrishna\AppData\Local\Temp\pip-install-5ubivpei\autopy_7e1ad0be51014a269e1b67ffbe2e7e98\setup.py", line 8, in <module>
        from setuptools_rust import Binding, RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/c6/36/bb1af0948e12cedef71da68b80960b3905805e30990d934102dcab012ddf/autopy-1.1.1.tar.gz#sha256=3cd7eb117adec743aec96c072b33e0c545c3fe31bbc5cf55e8217d76bf5919db (from https://pypi.org/simple/autopy/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached autopy-1.1.0.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\saikrishna\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Saikrishna\\AppData\\Local\\Temp\\pip-install-5ubivpei\\autopy_3a1ed6da43d54ddda55cf165a90b9670\\setup.py'"'"'; __file__='"'"'C:\\Users\\Saikrishna\\AppData\\Local\\Temp\\pip-install-5ubivpei\\autopy_3a1ed6da43d54ddda55cf165a90b9670\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Saikrishna\AppData\Local\Temp\pip-pip-egg-info-xoc6ywkx'
         cwd: C:\Users\Saikrishna\AppData\Local\Temp\pip-install-5ubivpei\autopy_3a1ed6da43d54ddda55cf165a90b9670\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Saikrishna\AppData\Local\Temp\pip-install-5ubivpei\autopy_3a1ed6da43d54ddda55cf165a90b9670\setup.py", line 8, in <module>
        from setuptools_rust import Binding, RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/c7/97/1246bc7b0fa62fa5a32e7182a6c2946e438ab6a3ff4907e617a8c30cfcb9/autopy-1.1.0.tar.gz#sha256=aab409369fb40c5a71b444c1e1b1db3278d888998a01d8924ce0af08643ad8e5 (from https://pypi.org/simple/autopy/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached autopy-1.0.1.tar.gz (16 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\saikrishna\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Saikrishna\\AppData\\Local\\Temp\\pip-install-5ubivpei\\autopy_fe8c24c1d7234cb2909116713e01b5c8\\setup.py'"'"'; __file__='"'"'C:\\Users\\Saikrishna\\AppData\\Local\\Temp\\pip-install-5ubivpei\\autopy_fe8c24c1d7234cb2909116713e01b5c8\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Saikrishna\AppData\Local\Temp\pip-pip-egg-info-ymwpi24t'
         cwd: C:\Users\Saikrishna\AppData\Local\Temp\pip-install-5ubivpei\autopy_fe8c24c1d7234cb2909116713e01b5c8\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Saikrishna\AppData\Local\Temp\pip-install-5ubivpei\autopy_fe8c24c1d7234cb2909116713e01b5c8\setup.py", line 5, in <module>
        from setuptools_rust import Binding, RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/cb/99/9203ea5442f3bd52695fce191305eeb6de63ff29a9a05d0c5ecb60ec4a69/autopy-1.0.1.tar.gz#sha256=889d80c1c11c25ba143cc748a152d36c3035a505f0f8a9049bc71bce4e591230 (from https://pypi.org/simple/autopy/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached autopy-1.0.0.tar.gz (16 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\saikrishna\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Saikrishna\\AppData\\Local\\Temp\\pip-install-5ubivpei\\autopy_669c0328e43b4cf891d38f801fe4f736\\setup.py'"'"'; __file__='"'"'C:\\Users\\Saikrishna\\AppData\\Local\\Temp\\pip-install-5ubivpei\\autopy_669c0328e43b4cf891d38f801fe4f736\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Saikrishna\AppData\Local\Temp\pip-pip-egg-info-1q_ismyw'
         cwd: C:\Users\Saikrishna\AppData\Local\Temp\pip-install-5ubivpei\autopy_669c0328e43b4cf891d38f801fe4f736\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Saikrishna\AppData\Local\Temp\pip-install-5ubivpei\autopy_669c0328e43b4cf891d38f801fe4f736\setup.py", line 5, in <module>
        from setuptools_rust import Binding, RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/6b/91/61349581c9c0dadd98ba5f946da1b546d649ee816b4150d641216c9e38a1/autopy-1.0.0.tar.gz#sha256=8b8d9ec9e96299b1ef791a71a8a2476d63de1b0f1a5a6cb9d5258a0294c9157d (from https://pypi.org/simple/autopy/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached autopy-0.51.tar.gz (74 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\saikrishna\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Saikrishna\\AppData\\Local\\Temp\\pip-install-5ubivpei\\autopy_64920196ca5049b4a6a7558aa2276913\\setup.py'"'"'; __file__='"'"'C:\\Users\\Saikrishna\\AppData\\Local\\Temp\\pip-install-5ubivpei\\autopy_64920196ca5049b4a6a7558aa2276913\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Saikrishna\AppData\Local\Temp\pip-pip-egg-info-wywdnr8p'
         cwd: C:\Users\Saikrishna\AppData\Local\Temp\pip-install-5ubivpei\autopy_64920196ca5049b4a6a7558aa2276913\
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Saikrishna\AppData\Local\Temp\pip-install-5ubivpei\autopy_64920196ca5049b4a6a7558aa2276913\setup.py", line 50
        print 'Updating __init__.py'
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Updating __init__.py')?
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/93/d7/209f9faed7eddfeec03f2353f9d53ea93ba6cb1c92e657467d4fa6e45dba/autopy-0.51.tar.gz#sha256=9d407110433bce7e5f6aef046c0a074f550c4a8d7dac069373727ab53d171e96 (from https://pypi.org/simple/autopy/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached autopy-0.5.tar.gz (74 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\saikrishna\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Saikrishna\\AppData\\Local\\Temp\\pip-install-5ubivpei\\autopy_c8d58d784f1940bfbe72383ffbf8e69e\\setup.py'"'"'; __file__='"'"'C:\\Users\\Saikrishna\\AppData\\Local\\Temp\\pip-install-5ubivpei\\autopy_c8d58d784f1940bfbe72383ffbf8e69e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Saikrishna\AppData\Local\Temp\pip-pip-egg-info-khxke5hj'
         cwd: C:\Users\Saikrishna\AppData\Local\Temp\pip-install-5ubivpei\autopy_c8d58d784f1940bfbe72383ffbf8e69e\
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Saikrishna\AppData\Local\Temp\pip-install-5ubivpei\autopy_c8d58d784f1940bfbe72383ffbf8e69e\setup.py", line 50
        print 'Updating __init__.py'
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Updating __init__.py')?
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/af/bc/7a0dc66717e11eac17361f66779884dace6632a35a6023701babb89835bb/autopy-0.5.tar.gz#sha256=7918f7757cccbb9bf5445973d9051b640bfb8cfa13f89e15c351aee5a014646d (from https://pypi.org/simple/autopy/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement autopy (from versions: 0.5, 0.51, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 4.0.0)
ERROR: No matching distribution found for autopy--------------

(What happened instead? How is it different from what you expected?)

```
(If the library threw an exception, paste the full stack trace here)
```

System information
------------------

(Delete all the statements that don't apply.)

My **system** is <INSERT SYSTEM HERE>. (For example, "Ubuntu 16.04 LTS x64", "Windows 10 x64", or "macOS Sierra".)

My **Python version** is <INSERT VERSION HERE>. (You can check this by running `python -V`.)

My **Pip version** is <INSERT VERSION HERE>. (You can check this by running `pip -V`.)

My **SpeechRecognition library version** is <INSERT VERSION HERE>. (You can check this by running `python -c "import speech_recognition as sr;print(sr.__version__)"`.)

My **PyAudio library version** is <INSERT VERSION HERE> / I don't have PyAudio installed. (You can check this by running `python -c "import pyaudio as p;print(p.__version__)"`.)

My **microphones** are: (You can check this by running `python -c "import speech_recognition as sr;print(sr.Microphone.list_microphone_names())"`.)

My **working microphones** are: (You can check this by running `python -c "import speech_recognition as sr;print(sr.Microphone.list_working_microphones())"`.)

I **installed PocketSphinx from** <INSERT SOURCE HERE>. (For example, from the Debian repositories, from Homebrew, or from the source code.)

**Comment by ssk1504** [comment]
please solve this . ineed it very badly

**Comment by amcareem** [comment]
Did you update it?
