### ISSUE TITLE
Facing issues in installing pyaudio

### ISSUE THREAD

**Issue by Smruti1998** [Uberi/speech_recognition#599]
I'm constantly getting this error, please give me solution for this,

Defaulting to user installation because normal site-packages is not writeable
Collecting pyaudio
  Using cached PyAudio-0.2.11.tar.gz (37 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "C:\Program Files\Python310\setuptools\__init__.py", line 2, in <module>
          from setuptools.extension import Extension, Library
        File "C:\Program Files\Python310\setuptools\extension.py", line 5, in <module>
          from setuptools.dist import _get_unpatched
        File "C:\Program Files\Python310\setuptools\dist.py", line 103
          except ValueError, e:
                 ^^^^^^^^^^^^^
      SyntaxError: multiple exception types must be parenthesized
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by NikitinGs** [comment]
PIP's PyAudio doesn't support python 3.10. Download it from here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyaudio and install it via pip install %actualPackageName% ran in the downloaded directory
