### ISSUE TITLE
If I try to write my own code I get 'AttributeError'

### ISSUE THREAD

**Issue by veralfre** [Uberi/speech_recognition#68]
```python
import speech_recognition as sr

recognizer=sr.Recognizer()
mic=sr.Microphone()
print('Di qualcosa')
audio=recognizer.listen(mic)

try:
    text=recognizer.recognize_google(language='it')
    print('Hai detto: '+text)
except sr.UnknownValueError:
    print('Errore 1')
except sr.RequestError:
    print('Errore 2')


This code should be identical to your examples, but when I try to run it I get:

Traceback (most recent call last):
  File "C:/Users/Freddy/PycharmProjects/SpeechRecognition/SpeechToText.py", line 26, in <module>
    audio=recognizer.listen(mic)
  File "C:\Python34\lib\site-packages\speech_recognition\__init__.py", line 293, in listen
    buffer = source.stream.read(source.CHUNK)
AttributeError: 'NoneType' object has no attribute 'read'
```

So, what's the problem with my code?

**Comment by Uberi** [comment]
Hi @veralfre:

The microphone is a context manager. You need to open it in order to use it. Please see the [very first provided example](https://github.com/Uberi/speech_recognition/blob/master/examples/microphone_recognition.py).

In other words, the microphone needs to be entered using a `with` statement. This version of your code works:

```python
import speech_recognition as sr

r=sr.Recognizer()
with sr.Microphone() as mic:
    print('Di qualcosa')
    audio=r.listen(mic)

try:
    text=r.recognize_google(language='it')
    print('Hai detto: '+text)
except sr.UnknownValueError:
    print('Errore 1')
except sr.RequestError:
    print('Errore 2')
```

**Comment by immu0001** [comment]
@Uberi I have tried "with" but i am getting same "attribute error!!"
