### ISSUE TITLE
Background Microphone Example Causes Thread Exception

### ISSUE THREAD

**Issue by mhorn71** [Uberi/speech_recognition#70]
I've been trying to use the background microphone example and I keep getting a thread exception when running the example.

Google Speech Recognition thinks you said hello
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/speech_recognition/__init__.py", line 354, in threaded_listen
    audio = self.listen(s, 1)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/speech_recognition/__init__.py", line 293, in listen
    buffer = source.stream.read(source.CHUNK)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyaudio.py", line 605, in read
    return pa.read_stream(self._stream, num_frames)
OSError: [Errno Input overflowed] -9981

Any ideas why I get this error? 

Many thanks

Mark

**Comment by Uberi** [comment]
Hi @mhorn71,

Which PyAudio version do you have? If 0.2.8, have you tried upgrading to 0.2.9?

**Comment by mhorn71** [comment]
I have 0.2.8 I'll try upgrading to 0.2.9

**Comment by mhorn71** [comment]
Ok upgraded to Pyaudio 0.2.9 and I get the same error. 

Google Speech Recognition thinks you said hello
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/speech_recognition/__init__.py", line 354, in threaded_listen
    audio = self.listen(s, 1)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/speech_recognition/__init__.py", line 293, in listen
    buffer = source.stream.read(source.CHUNK)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PyAudio-0.2.9-py3.4-macosx-10.11-x86_64.egg/pyaudio.py", line 609, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
OSError: [Errno -9981] Input overflowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/speech_recognition/__init__.py", line 358, in threaded_listen
    if running[0]: callback(self, audio)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/speech_recognition/__init__.py", line 80, in __exit__
    if not self.stream.is_stopped():
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PyAudio-0.2.9-py3.4-macosx-10.11-x86_64.egg/pyaudio.py", line 544, in is_stopped
    return pa.is_stream_stopped(self._stream)
OSError: [Errno -9988] Stream closed

**Comment by mhorn71** [comment]
It looks after a bit of googling I found an old Mac OSX issue with PyAudio that causes the input overflow apparently it was fixed but obviously is still present in some cases.  I come across a workaround  using a 'try, except' statement.  I've tried this and though I no longer get the input overflow I still get an OSError but I'm at a loss what to do about that. 

For the ambient noise I changed the stream.read in __init__.py to

try:     buffer = stream.read(CHUNK)  except IOError:     buffer = '\x00' * source.CHUNK

for all others to

try:     buffer = stream.read(CHUNK)  except IOError:     buffer = ‘’

I don't know if that improved things  as I still get the OSError with self.stream.is_stopped() I'm floundering in a sea of far more complicated code than I'm use to.  If that doesn't help sorry to take up your time.

**Comment by Uberi** [comment]
Hi @mhorn71,

After some debugging, it seems to be an issue with PyAudio and OS X. That means it's related to #70 and #71.

Can you try this? Replace `with Microphone() as m:` with the following:

```python
m = Microphone()
m.SAMPLE_RATE = 48000
with m:
   # stuff goes here
```

Also, what is the output of the following?

```python
import pyaudio
p = pyaudio.PyAudio()
p.get_device_info_by_index(0) # NOTE:replace 0 with the device index you're using if it's not already 0
```

**Comment by orgicus** [comment]
Hi,

I think running into a similar situation. I've tried modified the sample:
```python
#!/usr/bin/env python3

# NOTE: this example requires PyAudio because it uses the Microphone class

from speech_recognition import Microphone
import speech_recognition as sr


print Microphone.list_microphone_names()

# obtain audio from the microphone
r = sr.Recognizer()
audio = None
with sr.Microphone(device_index=0) as source:
    # OSX may use 48KHz instead of 44KHz ?
    sr.SAMPLE_RATE = 48000
    print("Say something!")
    try:
        audio = r.listen(source)
    except TypeError as e:
        print("error; {0}".format(e))    

if audio == None:
    print "error getting audio"
    exit()

# recognize speech using Sphinx
try:
    print("Sphinx thinks you said " + r.recognize_sphinx(audio))
except sr.UnknownValueError:
    print("Sphinx could not understand audio")
except sr.RequestError as e:
    print("Sphinx error; {0}".format(e))

# recognize speech using Google Speech Recognition
try:
    # for testing purposes, we're just using the default API key
    # to use another API key, use `r.recognize_google(audio, key="GOOGLE_SPEECH_RECOGNITION_API_KEY")`
    # instead of `r.recognize_google(audio)`
    print("Google Speech Recognition thinks you said " + r.recognize_google(audio))
except sr.UnknownValueError:
    print("Google Speech Recognition could not understand audio")
except sr.RequestError as e:
    print("Could not request results from Google Speech Recognition service; {0}".format(e))
```

I get this output:
```
[u'Built-in Microph', u'Built-in Input', u'Built-in Output', u'Soundflower (2ch)', u'Soundflower (64ch)', u'After Effects 13.5', u'Premiere Pro 7.0', u'Soundbooth 3.0', u'stest', u'Aggregate Device']
Say something!
error; read() got an unexpected keyword argument 'exception_on_overflow'
error getting audio
```
The main issue is:
```
error; read() got an unexpected keyword argument 'exception_on_overflow'
```

if it helps:
```
pyaudio.__version__
'0.2.7'
pyaudio.get_portaudio_version()
1899L
```

Any hints on how I can get past this error :D ?

Thank you,
George

**Comment by jbwincek** [comment]
Are you running the absolute most current version of speech_recognition (3.2.1 uploaded to pypy today-ish)? It contains pull request #82  which I think fixes the issue you're having.

**Comment by Uberi** [comment]
Hey @orgicus,

In your case, you should update PyAudio, v0.2.7 is nearly 4 years old!

For everyone else, please update to SpeechRecognition 3.2.1, which should have a fix for this issue.

**Comment by s4chin** [comment]
Just so you know, I also had the same problem that @orgicus had. I used version 3.3.1. The problem didn't exist when I was using the old version i.e. 3.1.3. So I reverted back to it and it works.

**Comment by Uberi** [comment]
Hi @s4chin,

Glad you've got it working. If you'd like to use the latest version, simply ensure that you have PyAudio 0.2.9. Note that many package repositories haven't updated this yet, so it may need to be installed via Pip.

**Comment by aferriss** [comment]
FWIW I'm getting an error on OSX also with speech_recognition 3.3.3 and pyaudio 0.2.9. I also worked through all my device indices so I'm fairly sure it's not that.

```
import speech_recognition as sr

r = sr.Recognizer()

audio = None
with sr.Microphone(device_index=0) as source:
	sr.SAMPLE_RATE = 48000
	try:
		audio = r.listen(source)
	except TypeError as e:
		print("error; {0}".format(e))
```

gives me
`error; function takes exactly 2 arguments (3 given)`

stemming from the read function in pyaudio..full output:

```
Traceback (most recent call last):
  File "micTest.py", line 9, in <module>
    audio = r.listen(source)
  File "/usr/local/lib/python2.7/site-packages/speech_recognition/__init__.py", line 390, in listen
    buffer = source.stream.read(source.CHUNK)
  File "/usr/local/lib/python2.7/site-packages/speech_recognition/__init__.py", line 134, in read
    return self.pyaudio_stream.read(size, exception_on_overflow = False)
  File "/usr/local/lib/python2.7/site-packages/pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
TypeError: function takes exactly 2 arguments (3 given)
```

**Comment by Uberi** [comment]
Hi @aferriss,

I missed your issue earlier since it was a comment on an already-closed one.

It seems like your PortAudio version is too old. Are you using precompiled binaries? If you're compiling your own, what PortAudio version are you using?

**Comment by rahulmis** [comment]
raceback (most recent call last):
  File "C:/Users/ASUS/PycharmProjects/p3.6/speechtotext.py", line 5, in <module>
    with mic as source:
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\speech_recognition\__init__.py", line 141, in __enter__
    input=True,  # stream is an input stream
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9999] Unanticipated host error




why i am getting this error
