### ISSUE TITLE
AttributeError: 'Recognizer' object has no attribute 'recognize_google'

### ISSUE THREAD

**Issue by RehanShk** [Uberi/speech_recognition#744]
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jetson/.local/lib/python3.8/site-packages/speech_recognition/__init__.py", line 568, in threaded_listen
    if running[0]: callback(self, audio)
  File "/home/jetson/FYP/Main.py", line 24, in callback
    command = recognizer.recognize_google(audio).lower()
AttributeError: 'Recognizer' object has no attribute 'recognize_google'

I am using background_listening example of speech_recognition, It was working fine everytime I was using it, but after I installed deepface, its giving me above error

**Comment by ftnext** [comment]
@RehanShk Please report according to [the issue template](https://github.com/Uberi/speech_recognition/issues/new).
It is also helpful to share the entire traceback and the whole script.
