### ISSUE TITLE
ValueError when attempting to run Microphone_recognition.py

### ISSUE THREAD

**Issue by traw1234** [Uberi/speech_recognition#90]
I followed all of the steps for the installation, though when I attempt to run the microphone_recognition.py code, I get the following error: 

If this means anything, this message continues to appear when I attempt to run the program:

2016-03-01 16:11:02.771 Python[55310:875154] 16:11:02.770 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.

I am running this off of OS X El Capitan. 

Steps to reproduce
------------------

1. Open Terminal
2. Run 'python testcv.py'
3. The following message appears:

2016-03-01 16:41:32.474 Python[56004:920490] 16:41:32.473 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.

4: "Say Something!" appears on the screen
5. I received a ValueError for PyCapsule
6. The program stops running

Expected behaviour
------------------

I expected the voice recognition program to run, rather than displaying errors.

Actual behaviour
----------------

The program stopped running and I received the following errors: 

Traceback (most recent call last):
  File "/Users/**xxxxxx**/Desktop/testcv.py", line 15, in <module>
    print("Sphinx thinks you said " + r.recognize_sphinx(audio))
  File "/usr/local/lib/python2.7/site-packages/speech_recognition/__init__.py", line 466, in recognize_sphinx
    from pocketsphinx import pocketsphinx
  File "build/bdist.macosx-10.11-x86_64/egg/pocketsphinx.py", line 7, in <module>
  File "build/bdist.macosx-10.11-x86_64/egg/pocketsphinx.py", line 6, in __bootstrap__
  File "sphinxbase.pxd", line 150, in init pocketsphinx (pocketsphinx.c:7935)
ValueError: PyCapsule_GetPointer called with invalid PyCapsule object

System information
------------------

Macbook Pro running OS X El Capitan 10.11

My **SpeechRecognition library version** is 3.3.1.

My **PyAudio library version** is 0.2.9 

I **installed PocketSphinx from** Homebrew.

**Comment by Uberi** [comment]
Please follow the issue template. In particular, the steps to reproduce, the code, and the environment values.

**Comment by Uberi** [comment]
This issue is caused by installing Pocketsphinx from Homebrew, which currently has version 0.0.8.

0.0.8 is too old to work with this library. Please follow the [official installation instructions](https://github.com/Uberi/speech_recognition/blob/master/reference/pocketsphinx.rst#building-pocketsphinx-python-from-source) and install a more recent version of Pocketsphinx using Pip.

To summarize:

    brew install swig git python
    pip install pocketsphinx
